@extends('layouts.public')

@php
    $siteName = $brand['name'] ?? config('fuelfree.company.name');
@endphp

@section('title', $siteName)

@section('content')
<style>
:root{--bg:#031018;--panel:#071b26;--line:rgba(83,218,240,.16);--text:#effcff;--muted:#91aeb8;--cyan:#48d8f1;--max:1180px}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% 0,rgba(33,187,221,.13),transparent 30%),linear-gradient(180deg,#020a10,#061721 55%,#020a10);color:var(--text);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}a{text-decoration:none;color:inherit}.shell{width:min(var(--max),calc(100% - 32px));margin:auto}.welcome{padding:88px 0 72px;text-align:center}.eyebrow{color:var(--cyan);font-size:12px!important;letter-spacing:.2em;text-transform:uppercase}.welcome h1{font-size:clamp(42px,7vw,82px);line-height:.98;letter-spacing:-.06em;margin:15px auto;max-width:900px}.welcome h1 em{font-style:normal;color:#a9f5ff}.welcome p{max-width:700px;margin:0 auto;color:var(--muted);font-size:16px!important;line-height:1.9}.section{padding:42px 0}.head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:24px}.head h2{font-size:clamp(28px,4vw,45px);letter-spacing:-.04em;margin:5px 0}.more{font-size:13px!important;color:var(--cyan);white-space:nowrap}
.news-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.news{position:relative;display:grid;grid-template-columns:180px minmax(0,1fr);min-height:190px;overflow:hidden;border:1px solid var(--line);border-radius:16px;background:linear-gradient(145deg,rgba(8,37,50,.92),rgba(3,19,27,.96));transition:transform .25s,border-color .25s,box-shadow .25s}.news:hover{transform:translateY(-3px);border-color:rgba(72,216,241,.4);box-shadow:0 14px 32px rgba(0,0,0,.16)}.news-media{width:180px;height:100%;min-height:190px;background:#061923;overflow:hidden;position:relative}.news-media img{width:100%;height:100%;display:block;object-fit:cover}.news-kind{position:absolute;top:12px;left:12px;padding:5px 8px;border-radius:6px;background:rgba(2,12,18,.82);border:1px solid rgba(72,216,241,.2);color:var(--cyan);font-size:9px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.news-kind.notice{color:#f0c58e;border-color:rgba(240,197,142,.25)}.news-body{padding:18px 18px 16px;display:flex;flex-direction:column;min-width:0}.news h3{margin:0 0 9px;font-size:18px;line-height:1.32;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.news p{color:var(--muted);font-size:13px!important;line-height:1.65!important;margin:0;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.news-footer{margin-top:auto;padding-top:14px;display:flex;align-items:center;justify-content:space-between;gap:8px}.date{color:#6f9aa5;font-size:11px!important}.read{color:var(--cyan);font-size:11px!important;font-weight:700;white-space:nowrap}
.folders{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.folder{position:relative;display:block;border:1px solid var(--line);border-radius:16px;overflow:hidden;background:linear-gradient(145deg,rgba(8,37,50,.92),rgba(3,19,27,.96));transition:transform .25s,border-color .25s,box-shadow .25s}.folder:hover{transform:translateY(-4px);border-color:rgba(72,216,241,.4);box-shadow:0 18px 40px rgba(0,0,0,.18)}.folder-media{width:100%;aspect-ratio:16/9;overflow:hidden;background:#061923}.folder-media img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .55s ease}.folder:hover .folder-media img{transform:scale(1.035)}.folder-placeholder{width:100%;height:100%;display:grid;place-items:center;color:#4fd2ee;font-size:42px}.folder-body{padding:15px 17px 16px}.folder-body h3{margin:0 0 10px;font-size:17px;line-height:1.35;letter-spacing:-.015em;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.folder-meta{display:flex;align-items:center;justify-content:space-between;gap:12px;color:#8daab5;font-size:11px!important}.folder-count{color:#72dfbf;white-space:nowrap}.folder-count i,.folder-date i{color:var(--cyan);margin-right:5px}.empty{padding:35px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:18px}
@media(min-width:1100px){.news-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.news{display:block;min-height:0}.news-media{width:100%;height:190px;min-height:190px}.news-body{min-height:190px}.folders{grid-template-columns:repeat(3,minmax(0,1fr))}}
@media(max-width:900px) and (min-width:651px){.news-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.news{grid-template-columns:145px minmax(0,1fr)}.news-media{width:145px;min-height:175px}.news-body{min-height:175px}.folders{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:650px){.welcome{padding:65px 0 48px}.welcome h1{font-size:45px}.head{align-items:center;margin-bottom:16px}.head h2{font-size:clamp(25px,7vw,34px);line-height:1.05;white-space:nowrap}.more{font-size:10px!important}.news-grid{grid-template-columns:1fr;gap:10px}.news{grid-template-columns:112px 24px minmax(0,1fr);width:100%;height:112px;min-height:112px}.news-media{width:112px;height:112px;min-width:112px;min-height:112px}.news-media img{width:112px;height:112px}.news-kind{position:static;height:100%;padding:0;background:transparent;border:0;border-right:1px solid rgba(72,216,241,.1);border-radius:0;display:flex;align-items:center;justify-content:center;writing-mode:vertical-rl;transform:rotate(180deg);font-size:7px}.news-body{height:112px;min-height:112px;padding:11px 13px}.news h3{font-size:14px;line-height:1.3;margin:0;-webkit-line-clamp:2}.news p{display:none}.news-footer{padding-top:5px}.date{font-size:8px!important}.read{font-size:8px!important}.folders{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.folder-body{padding:11px}.folder-body h3{font-size:13px;margin-bottom:8px}.folder-meta{font-size:8px!important;display:block}.folder-count{display:block;margin-top:4px}}
@media(max-width:400px){.news{grid-template-columns:100px 22px minmax(0,1fr);height:100px;min-height:100px}.news-media{width:100px;height:100px;min-width:100px;min-height:100px}.news-media img{width:100px;height:100px}.news-body{height:100px;min-height:100px;padding:9px 11px}.news h3{font-size:13px}.shell{width:calc(100% - 22px)}}
</style>
<main class="shell">
    <section class="welcome"><span class="eyebrow">Welcome to {{ $siteName }}</span><h1>Building a <em>stronger</em> energy future.</h1><p>{{ $brand['tagline'] }} We welcome you to explore our latest company news, activities and photo galleries.</p></section>
    <section class="section"><div class="head"><div><span class="eyebrow">Latest updates</span><h2>News &amp; Notices</h2></div><a class="more" href="{{ route('news.index') }}">View all →</a></div><div class="news-grid">@if(($content['news']??collect())->isNotEmpty())@foreach(($content['news']??collect())->take(6) as $item)<a class="news" href="{{ route('news.show',$item->slug) }}"><div class="news-media">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" alt="{{ $item->cover_alt ?: $item->title }}" loading="lazy">@else<div class="news-placeholder">▣</div>@endif</div><div class="news-kind {{ $item->type==='announcement'?'notice':'' }}">{{ $item->type==='announcement'?'Notice':'News' }}</div><div class="news-body"><h3>{{ $item->title }}</h3><p>{{ $item->excerpt ?: \Illuminate\Support\Str::limit(strip_tags((string) $item->content), 180) }}</p><div class="news-footer"><span class="date">{{ $item->published_at?->format('d F Y') }}</span><span class="read">Read more →</span></div></div></a>@endforeach @else<div class="empty" style="grid-column:1/-1">No news has been published yet.</div>@endif</div></section>
    <section class="section"><div class="head"><div><span class="eyebrow">Photo collections</span><h2>Gallery</h2></div><a class="more" href="{{ route('site.gallery') }}">View all →</a></div><div class="folders">@if($gallery->isNotEmpty())@foreach($gallery->take(8) as $item)<a class="folder" href="{{ route('gallery.show',$item->id) }}"><div class="folder-media">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" alt="{{ $item->title }}" loading="lazy">@else<div class="folder-placeholder">▣</div>@endif</div><div class="folder-body"><h3>{{ $item->title }}</h3><div class="folder-meta"><span class="folder-date"><i class="fa-regular fa-calendar-days"></i>{{ $item->published_at?->format('d F Y') ?? 'Unpublished' }}</span><span class="folder-count"><i class="fa-regular fa-images"></i>{{ $item->gallery_media_count }} photos</span></div></div></a>@endforeach @else<div class="empty" style="grid-column:1/-1">No photo galleries have been published yet.</div>@endif</div></section>
</main>
@endsection
