<!doctype html>
<html lang="{{ str_replace('_','-',app()->getLocale()) }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="{{ $brand['tagline'] }}">
<title>{{ $brand['name'] }}</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
<style>
:root{--bg:#020b12;--panel:#061a25;--panel2:#082433;--line:rgba(86,210,238,.16);--text:#effcff;--muted:#8eabb7;--cyan:#43d1f0;--cyan2:#159fc5;--green:#45e0ad;--shadow:0 25px 70px rgba(0,0,0,.3)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden}a{color:inherit;text-decoration:none}.shell{width:min(1180px,calc(100% - 32px));margin:auto}.site-header{position:sticky;top:0;z-index:50;background:rgba(2,11,18,.78);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}.nav{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{display:flex;align-items:center;gap:11px;min-width:0}.brand img{width:42px;height:42px;object-fit:contain;border-radius:11px}.brand-name{font-weight:850;letter-spacing:.02em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.brand-name .fuel{color:#52cdf0}.brand-name .power{color:#f2fbff}.menu{display:flex;align-items:center;gap:3px}.menu a{font-size:11px;color:#9db7c0;padding:10px 11px;border-radius:10px;transition:.2s}.menu a:hover{color:#fff;background:rgba(67,209,240,.08)}.menu i{margin-right:6px;color:#64d8f2}.menu-btn{display:none;width:43px;height:43px;border:1px solid var(--line);border-radius:13px;background:rgba(255,255,255,.035);color:#dff9ff;font-size:18px;align-items:center;justify-content:center}.energy-bg{position:fixed;inset:0;pointer-events:none;overflow:hidden;z-index:-1;background:radial-gradient(circle at 50% 20%,rgba(18,145,184,.18),transparent 30%),radial-gradient(circle at 15% 75%,rgba(22,91,126,.13),transparent 30%),linear-gradient(180deg,#020a11,#03131d 50%,#020a11)}.energy-bg:before{content:"";position:absolute;inset:-30%;background:repeating-radial-gradient(circle at 50% 50%,transparent 0 95px,rgba(57,203,237,.035) 96px 97px);animation:drift 28s linear infinite}.energy-bg:after{content:"";position:absolute;inset:0;background-image:linear-gradient(115deg,transparent 0 48%,rgba(55,205,238,.045) 49%,transparent 50%),linear-gradient(65deg,transparent 0 49%,rgba(55,205,238,.035) 50%,transparent 51%);background-size:260px 260px,330px 330px;mask-image:linear-gradient(to bottom,black,transparent 85%);animation:gridMove 20s linear infinite}.energy-pulse{position:absolute;width:2px;height:130px;background:linear-gradient(transparent,var(--cyan),transparent);filter:drop-shadow(0 0 8px var(--cyan));opacity:.28;animation:fall 5s linear infinite}.p1{left:11%;top:-120px}.p2{left:74%;top:-180px;animation-delay:2s}.p3{left:91%;top:-100px;animation-delay:3.5s}@keyframes drift{to{transform:rotate(360deg)}}@keyframes gridMove{to{background-position:260px 260px,-330px 330px}}@keyframes fall{to{transform:translateY(120vh)}}
.hero{position:relative;min-height:650px;display:grid;grid-template-columns:1.08fr .92fr;align-items:center;gap:35px;padding:80px 0 70px}.hero-copy{position:relative;z-index:2}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--cyan);font-size:10px;letter-spacing:.2em;text-transform:uppercase}.eyebrow:before{content:"";width:22px;height:1px;background:var(--cyan);box-shadow:0 0 10px var(--cyan)}.hero h1{font-size:clamp(46px,7vw,82px);line-height:.96;letter-spacing:-.055em;margin:18px 0 20px}.hero h1 .accent{color:var(--cyan);text-shadow:0 0 28px rgba(67,209,240,.18)}.hero p{max-width:650px;color:var(--muted);font-size:17px;line-height:1.8;margin:0}.actions{display:flex;gap:11px;flex-wrap:wrap;margin-top:30px}.btn{display:inline-flex;align-items:center;gap:9px;padding:13px 17px;border-radius:12px;background:linear-gradient(135deg,#37c5e6,#168faf);font-weight:800;font-size:12px;box-shadow:0 12px 30px rgba(25,164,200,.16)}.btn.secondary{background:rgba(255,255,255,.035);border:1px solid var(--line);box-shadow:none;color:#b8d2da}.hero-visual{height:430px;position:relative;display:grid;place-items:center}.core-ring{position:absolute;border:1px solid rgba(67,209,240,.17);border-radius:50%;box-shadow:inset 0 0 40px rgba(67,209,240,.035)}.r1{width:230px;height:230px;animation:spin 15s linear infinite}.r2{width:340px;height:340px;border-style:dashed;animation:spin 25s linear infinite reverse}.r3{width:420px;height:420px;opacity:.45;animation:spin 35s linear infinite}.core{width:145px;height:145px;border-radius:50%;display:grid;place-items:center;position:relative;background:radial-gradient(circle,#dffcff 0 4%,#4ed8f1 18%,#087899 45%,rgba(3,35,48,.1) 70%);box-shadow:0 0 50px rgba(67,209,240,.42),0 0 120px rgba(67,209,240,.16);animation:breath 3.4s ease-in-out infinite}.core:before{content:"";position:absolute;inset:-15px;border:1px solid rgba(67,209,240,.35);border-radius:50%;animation:corePulse 2.4s ease-out infinite}.core i{font-size:55px;color:white;filter:drop-shadow(0 0 14px rgba(255,255,255,.7))}@keyframes spin{to{transform:rotate(360deg)}}@keyframes breath{50%{transform:scale(1.07);box-shadow:0 0 80px rgba(67,209,240,.55),0 0 150px rgba(67,209,240,.2)}}@keyframes corePulse{to{transform:scale(1.65);opacity:0}}
.section{padding:72px 0}.section-head{display:flex;align-items:end;justify-content:space-between;gap:30px;margin-bottom:25px}.section-head h2{font-size:clamp(28px,4vw,42px);margin:8px 0 0;letter-spacing:-.035em}.section-head p{max-width:560px;color:var(--muted);line-height:1.7;font-size:13px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.stat,.card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(8,38,52,.9),rgba(3,21,30,.82));border-radius:19px;box-shadow:var(--shadow)}.stat{padding:21px;position:relative;overflow:hidden}.stat:after{content:"";position:absolute;width:90px;height:90px;border-radius:50%;right:-40px;top:-40px;background:rgba(67,209,240,.08)}.stat i{font-size:17px;color:var(--cyan)}.stat small{display:block;color:#7194a1;text-transform:uppercase;letter-spacing:.12em;font-size:9px;margin-top:17px}.stat strong{display:block;font-size:29px;margin-top:7px}.plant-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.plant{overflow:hidden}.plant-image{height:165px;background:linear-gradient(135deg,#0a2c3b,#061720);display:grid;place-items:center;position:relative}.plant-image img{width:100%;height:100%;object-fit:cover}.plant-image i{font-size:38px;color:#4fd5ef}.plant-body{padding:19px}.plant-top{display:flex;justify-content:space-between;gap:10px}.plant h3{margin:7px 0;font-size:18px}.pill{font-size:9px;padding:5px 8px;border-radius:999px;background:rgba(69,224,173,.1);color:#6ce7c3;height:max-content}.plant p{color:var(--muted);font-size:11px;line-height:1.65;min-height:54px}.meta{display:flex;gap:8px;flex-wrap:wrap;color:#91b5c0;font-size:9px}.content-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.content-card{padding:21px;min-height:185px}.content-card .type{font-size:9px;color:var(--cyan);text-transform:uppercase;letter-spacing:.14em}.content-card h3{font-size:18px;margin:11px 0}.content-card p{color:var(--muted);font-size:11px;line-height:1.65}.content-card time{color:#638794;font-size:9px}.cta{padding:30px;border-radius:24px;border:1px solid rgba(67,209,240,.2);background:radial-gradient(circle at 90% 20%,rgba(67,209,240,.16),transparent 35%),linear-gradient(135deg,rgba(9,45,61,.9),rgba(3,21,30,.9));display:flex;align-items:center;justify-content:space-between;gap:25px}.cta h2{margin:0 0 8px;font-size:27px}.cta p{margin:0;color:var(--muted);font-size:12px;line-height:1.6}.footer{border-top:1px solid var(--line);margin-top:30px;padding:35px 0 55px;color:#6e8e99;font-size:10px}.footer-grid{display:flex;justify-content:space-between;gap:25px;flex-wrap:wrap}.empty{padding:28px;border:1px dashed var(--line);border-radius:16px;color:var(--muted)}
@media(max-width:900px){.hero{grid-template-columns:1fr;min-height:auto}.hero-visual{height:330px;order:-1}.r3{width:320px;height:320px}.r2{width:260px;height:260px}.r1{width:190px;height:190px}.core{width:120px;height:120px}.stats{grid-template-columns:repeat(2,1fr)}.plant-grid,.content-grid{grid-template-columns:1fr 1fr}}
@media(max-width:700px){.menu-btn{display:flex}.menu{display:none;position:absolute;top:72px;left:12px;right:12px;padding:9px;flex-direction:column;align-items:stretch;background:rgba(3,17,25,.98);border:1px solid var(--line);border-radius:15px;box-shadow:0 22px 60px rgba(0,0,0,.4)}.menu.open{display:flex}.menu a{padding:12px}.section-head{display:block}.section-head p{margin-bottom:0}.cta{display:block}.cta .btn{margin-top:18px}}
@media(max-width:520px){.shell{width:calc(100% - 24px)}.nav{min-height:64px}.brand img{width:37px;height:37px}.brand-name{font-size:13px}.hero{padding:48px 0 35px}.hero h1{font-size:44px}.hero p{font-size:14px}.hero-visual{height:245px}.r3{width:245px;height:245px}.r2{width:200px;height:200px}.r1{width:150px;height:150px}.core{width:92px;height:92px}.core i{font-size:35px}.stats,.plant-grid,.content-grid{grid-template-columns:1fr}.stat strong{font-size:27px}.section{padding:48px 0}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}}
</style>
</head>
<body>
<div class="energy-bg" aria-hidden="true"><span class="energy-pulse p1"></span><span class="energy-pulse p2"></span><span class="energy-pulse p3"></span></div>
<header class="site-header"><div class="shell nav">
<a class="brand" href="{{ route('home') }}">@if($brand['logo_path'])<img src="{{ asset('storage/'.$brand['logo_path']) }}" alt="{{ $brand['name'] }}">@endif<span class="brand-name"><span class="fuel">{{ ​Str::before($brand['name'],' ') ?: $brand['name'] }}</span>@if(Str::contains($brand['name'],' ')) <span class="power">{{ Str::after($brand['name'],' ') }}</span>@endif</span></a>
<button class="menu-btn" type="button" aria-label="Open navigation menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button>
<nav class="menu" id="site-menu"><a href="{{ route('home') }}"><i class="fa-solid fa-house"></i>Home</a>@foreach($pages as $page)<a href="{{ route('cms.page',$page->slug) }}"><i class="fa-regular fa-file-lines"></i>{{ $page->title }}</a>@endforeach @auth<a href="{{ route('dashboard') }}"><i class="fa-solid fa-gauge-high"></i>Portal</a>@else<a href="{{ route('login') }}"><i class="fa-solid fa-right-to-bracket"></i>Login</a>@endauth</nav>
</div></header>
<main>
<section class="shell hero"><div class="hero-copy"><span class="eyebrow">Power infrastructure · clean energy</span><h1>{{ $homePage?->title ?? $brand['name'] }}</h1><p>{{ $homePage?->excerpt ?? $brand['tagline'] }}</p><div class="actions"><a class="btn" href="#projects"><i class="fa-solid fa-bolt"></i>Explore projects</a><a class="btn secondary" href="#company"><i class="fa-solid fa-building"></i>Our company</a></div></div><div class="hero-visual" aria-hidden="true"><div class="core-ring r3"></div><div class="core-ring r2"></div><div class="core-ring r1"></div><div class="core"><i class="fa-solid fa-bolt"></i></div></div></section>
<section class="section" id="overview"><div class="shell"><div class="section-head"><div><span class="eyebrow">Power at a glance</span><h2>Energy infrastructure, clearly presented.</h2></div><p>Live or verified plant figures will only appear when approved data is available. Until then, the platform keeps the public experience honest and data-driven.</p></div><div class="stats"><article class="stat"><i class="fa-solid fa-industry"></i><small>Power projects</small><strong>{{ $stats['projects'] }}</strong></article><article class="stat"><i class="fa-solid fa-bolt"></i><small>Installed capacity</small><strong>{{ number_format($stats['capacity_mw'],2) }} MW</strong></article><article class="stat"><i class="fa-solid fa-circle-check"></i><small>Operational</small><strong>{{ $stats['operational'] }}</strong></article><article class="stat"><i class="fa-solid fa-leaf"></i><small>Energy focus</small><strong>Clean</strong></article></div></div></section>
<section class="section" id="projects"><div class="shell"><div class="section-head"><div><span class="eyebrow">Power portfolio</span><h2>Projects &amp; power plants</h2></div><p>Every project shown here is sourced from the administration system and can be managed without editing the public page.</p></div>@if($plants->isEmpty())<div class="empty">No published power plant records are available yet.</div>@else<div class="plant-grid">@foreach($plants as $plant)<article class="card plant"><div class="plant-image">@if($plant->image_path)<img src="{{ asset('storage/'.$plant->image_path) }}" alt="{{ $plant->name }}">@else<i class="fa-solid fa-industry"></i>@endif</div><div class="plant-body"><div class="plant-top"><div><span class="eyebrow">{{ $plant->technology ?: 'Energy project' }}</span><h3>{{ $plant->name }}</h3></div><span class="pill">{{ $plant->status ?: 'Planned' }}</span></div><p>{{ $plant->overview ?: 'Project information will be published as the project record is completed.' }}</p><div class="meta"><span><i class="fa-solid fa-location-dot"></i> {{ $plant->location ?: 'Location pending' }}</span><span>•</span><span>{{ number_format((float)$plant->capacity_kw/1000,2) }} MW</span></div></div></article>@endforeach</div>@endif</div></section>
@if($content->has('company'))<section class="section" id="company"><div class="shell"><div class="section-head"><div><span class="eyebrow">Who we are</span><h2>Company</h2></div></div><div class="content-grid">@foreach($content->get('company')->take(3) as $item)<article class="card content-card"><span class="type">Company</span><h3>{{ $item->title }}</h3><p>{{ $item->excerpt ?: Str::limit(strip_tags($item->content),220) }}</p></article>@endforeach</div></div></section>@endif
@foreach(['management'=>'Management','news'=>'News & Updates','sustainability'=>'Sustainability','gallery'=>'Gallery','resource'=>'Resources','announcement'=>'Announcements'] as $type=>$heading)
@if($content->has($type))<section class="section" id="{{ $type }}"><div class="shell"><div class="section-head"><div><span class="eyebrow">{{ $heading }}</span><h2>{{ $heading }}</h2></div></div><div class="content-grid">@foreach($content->get($type)->take(6) as $item)<article class="card content-card"><span class="type">{{ $heading }}</span><h3>{{ $item->title }}</h3><p>{{ $item->excerpt ?: Str::limit(strip_tags($item->content),220) }}</p>@if($item->published_at)<time>{{ $item->published_at->format('d M Y') }}</time>@endif</article>@endforeach</div></div></section>@endif
@endforeach
<section class="section"><div class="shell"><div class="cta"><div><span class="eyebrow">FuelFree PowerPlant</span><h2>Building a cleaner energy future.</h2><p>{{ $brand['tagline'] }}</p></div><a class="btn" href="{{ $pages->first() ? route('cms.page',$pages->first()->slug) : '#overview' }}"><i class="fa-solid fa-arrow-right"></i>Discover more</a></div></div></section>
</main>
<footer class="footer"><div class="shell footer-grid"><div>© {{ date('Y') }} {{ $brand['name'] }}</div><div>{{ $brand['domain'] }} · {{ $brand['tagline'] }}</div></div></footer>
<script>document.addEventListener('DOMContentLoaded',()=>{const b=document.querySelector('.menu-btn'),m=document.querySelector('#site-menu');if(!b||!m)return;b.addEventListener('click',()=>{const open=m.classList.toggle('open');b.setAttribute('aria-expanded',open);b.setAttribute('aria-label',open?'Close navigation menu':'Open navigation menu');b.innerHTML=open?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>'});m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{m.classList.remove('open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation menu');b.innerHTML='<i class="fa-solid fa-bars"></i>'}))});</script>
</body></html>