@push('scripts')
<script>
(() => {
  const template = document.getElementById('ff-global-cms-editor-template');
  const sections = document.getElementById('npb-sections');
  const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
  const uploadUrl = @json(route('admin.cms.media'));
  if (!template || !sections) return;
  const states = new WeakMap(); const allStates = new Set();
  const escAttr = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const safeUrl = v => /^(javascript|data|vbscript):/i.test(String(v ?? '').trim()) ? '#' : String(v ?? '').trim() || '#';
  const blockOf = ed => { const s=window.getSelection(); let n=s?.anchorNode; if(!n||!ed.contains(n))return null; if(n.nodeType===3)n=n.parentElement; while(n&&n!==ed){if(/^(P|DIV|H[1-6]|BLOCKQUOTE|PRE|LI)$/.test(n.tagName))return n;n=n.parentElement} return null; };
  const saveSelection = st => {const s=window.getSelection();if(s?.rangeCount&&st.ed.contains(s.anchorNode))st.range=s.getRangeAt(0).cloneRange()};
  const restoreSelection = st => {if(!st.range)return;try{const s=window.getSelection();s.removeAllRanges();s.addRange(st.range)}catch(e){}};
  const status = st => {const b=blockOf(st.ed),tag=b?.tagName?.toLowerCase()||'p',names={p:'Paragraph',blockquote:'Quote',pre:'Code',h1:'Heading 1',h2:'Heading 2',h3:'Heading 3',h4:'Heading 4',h5:'Heading 5',h6:'Heading 6'};st.root.querySelector('[data-status-block]').textContent=names[tag]||'Paragraph';st.root.querySelector('[data-status-size]').textContent=b?getComputedStyle(b).fontSize:'—';const text=st.ed.innerText.replace(/\s+/g,' ').trim();st.root.querySelector('[data-count]').textContent=(text?text.split(/\s+/).length:0)+' words • '+text.length+' characters'};
  const buttons = st => ['bold','italic','underline','strikeThrough','insertUnorderedList','insertOrderedList','justifyLeft','justifyCenter','justifyRight','justifyFull'].forEach(cmd=>st.root.querySelectorAll(`[data-action="${cmd}"]`).forEach(b=>{let on=false;try{on=document.queryCommandState(cmd)}catch(e){}b.classList.toggle('active',on)}));
  const sync = st => {st.textarea.value=st.ed.innerHTML;st.textarea.dispatchEvent(new Event('input',{bubbles:true}));status(st)};
  const exec = (st,cmd,value=null) => {restoreSelection(st);st.ed.focus();try{document.execCommand('styleWithCSS',false,true)}catch(e){}try{document.execCommand(cmd,false,value)}catch(e){}sync(st);buttons(st)};
  const insert = (st,html) => {restoreSelection(st);st.ed.focus();try{document.execCommand('insertHTML',false,html)}catch(e){st.ed.insertAdjacentHTML('beforeend',html)}sync(st)};
  const upload = async file => {const fd=new FormData();fd.append('media',file);const r=await fetch(uploadUrl,{method:'POST',headers:{'X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:fd});if(!r.ok)throw new Error('Media upload failed for '+file.name);return r.json()};
  function init(root,textarea){if(states.has(textarea))return;const st={root,ed:root.querySelector('.ff-editable'),textarea,range:null,source:false,selected:null};states.set(textarea,st);allStates.add(st);st.ed.innerHTML=textarea.value||'';textarea.style.display='none';
    root.querySelectorAll('[data-tab]').forEach(tab=>tab.addEventListener('click',()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===tab));root.querySelectorAll('[data-panel]').forEach(p=>{const on=p.dataset.panel===tab.dataset.tab;p.classList.toggle('active',on);p.style.display=on?'flex':'none'});saveSelection(st)}));
    root.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>exec(st,b.dataset.action)));
    root.querySelector('[data-format]').addEventListener('change',e=>exec(st,'formatBlock',e.target.value));root.querySelector('[data-font]').addEventListener('change',e=>exec(st,'fontName',e.target.value));root.querySelector('[data-size]').addEventListener('change',e=>exec(st,'fontSize',e.target.value));root.querySelector('[data-fore]').addEventListener('input',e=>exec(st,'foreColor',e.target.value));root.querySelector('[data-highlight]').addEventListener('input',e=>exec(st,'hiliteColor',e.target.value));
    root.querySelector('[data-insert="link"]').addEventListener('click',()=>{const u=prompt('URL');if(u)exec(st,'createLink',safeUrl(u))});
    root.querySelector('[data-insert="button"]').addEventListener('click',()=>{const t=prompt('Button text','Learn More');if(!t)return;const u=prompt('Button URL','/');if(!u)return;const outline=prompt('Button style: primary or outline','primary')?.toLowerCase()==='outline';insert(st,`<a class="ff-cta ${outline?'outline':''}" href="${escAttr(safeUrl(u))}">${escAttr(t)}</a>&nbsp;`)});
    root.querySelector('[data-insert="columns"]').addEventListener('click',()=>{const n=Math.min(3,Math.max(2,Number(prompt('Number of columns (2 or 3)','2'))||2));insert(st,`<div class="ff-columns cols-${n}">${Array.from({length:n},(_,i)=>`<div class="ff-column"><h3>Column ${i+1}</h3><p>Click here to edit this content.</p></div>`).join('')}</div><p><br></p>`)});
    root.querySelector('[data-insert="table"]').addEventListener('click',()=>{const r=Math.min(20,Math.max(2,Number(prompt('Number of rows','3'))||3));const c=Math.min(10,Math.max(1,Number(prompt('Number of columns','3'))||3));insert(st,`<table><thead><tr>${Array.from({length:c},(_,i)=>`<th>Header ${i+1}</th>`).join('')}</tr></thead><tbody>${Array.from({length:r-1},()=>`<tr>${Array.from({length:c},()=>'<td>Cell</td>').join('')}</tr>`).join('')}</tbody></table><p><br></p>`)});
    root.querySelector('[data-insert="image-url"]').addEventListener('click',()=>{const u=prompt('Image URL');if(u)insert(st,`<img src="${escAttr(safeUrl(u))}" alt="Image" loading="lazy">`)});root.querySelector('[data-insert="video-url"]').addEventListener('click',()=>{const u=prompt('Video URL');if(u)insert(st,`<video controls preload="metadata" src="${escAttr(safeUrl(u))}"></video>`)});
    root.querySelector('[data-insert="youtube"]').addEventListener('click',()=>{const u=prompt('YouTube URL'),m=String(u||'').match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|shorts\/|embed\/))([^?&/]+)/);if(m)insert(st,`<iframe src="https://www.youtube.com/embed/${m[1]}" title="YouTube" allowfullscreen loading="lazy"></iframe>`);else if(u)alert('Please enter a valid YouTube URL.')});
    root.querySelector('[data-insert="facebook"]').addEventListener('click',()=>{const u=prompt('Facebook video URL');if(u)insert(st,`<iframe src="https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(u)}&show_text=false" title="Facebook" allowfullscreen loading="lazy"></iframe>`)});
    const media=root.querySelector('[data-media-input]');root.querySelector('[data-insert="media"]').addEventListener('click',()=>media.click());media.addEventListener('change',async()=>{const files=[...media.files];if(!files.length)return;try{const d=await Promise.all(files.map(upload));insert(st,d.map(x=>x.mime?.startsWith('video/')?`<video controls preload="metadata" src="${escAttr(x.url)}"></video>`:`<img src="${escAttr(x.url)}" alt="${escAttr(x.name||'Image')}" loading="lazy">`).join('<p><br></p>'))}catch(e){alert(e.message)}media.value='' });
    const gallery=root.querySelector('[data-gallery-input]');root.querySelector('[data-insert="gallery"]').addEventListener('click',()=>gallery.click());gallery.addEventListener('change',async()=>{const files=[...gallery.files];if(!files.length)return;try{const d=await Promise.all(files.map(upload));insert(st,`<div class="ff-gallery">${d.map(x=>`<img src="${escAttr(x.url)}" alt="${escAttr(x.name||'Image')}" loading="lazy">`).join('')}</div>`)}catch(e){alert(e.message)}gallery.value='' });
    root.querySelectorAll('[data-image-align]').forEach(b=>b.addEventListener('click',()=>{if(!st.selected){alert('Select an image first.');return}st.selected.classList.remove('ff-left','ff-center','ff-right');st.selected.classList.add('ff-'+b.dataset.imageAlign);sync(st);positionResize(st)}));
    root.querySelector('[data-view="source"]').addEventListener('click',()=>{st.source=!st.source;if(st.source){st.ed.textContent=st.ed.innerHTML;st.ed.classList.add('source-mode')}else{st.ed.innerHTML=st.ed.textContent;st.ed.classList.remove('source-mode');sync(st)}root.querySelector('[data-view="source"]').classList.toggle('active',st.source)});
    root.querySelector('[data-view="preview"]').addEventListener('click',()=>{if(st.source)root.querySelector('[data-view="source"]').click();const w=window.open('','_blank','width=1100,height=800');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Content Preview</title><style>body{font:16px/1.75 Arial;max-width:900px;margin:40px auto;padding:0 20px;color:#17252d}img,video,iframe{max-width:100%;height:auto}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccc;padding:8px}</style></head><body>${st.ed.innerHTML}</body></html>`);w.document.close()});
    root.querySelector('[data-view="fullscreen"]').addEventListener('click',()=>{root.classList.toggle('ff-fullscreen');const i=root.querySelector('[data-view="fullscreen"] i');if(i)i.className=root.classList.contains('ff-fullscreen')?'fa-solid fa-compress':'fa-solid fa-expand'});
    st.ed.addEventListener('click',e=>{const img=e.target.closest?.('img');if(img&&st.ed.contains(img)){st.root.querySelectorAll('img.ff-selected').forEach(x=>x.classList.remove('ff-selected'));st.selected=img;img.classList.add('ff-selected');positionResize(st)}else{if(st.selected)st.selected.classList.remove('ff-selected');st.selected=null;hideResize(st)}});
    ['input','keyup','mouseup','focus'].forEach(ev=>st.ed.addEventListener(ev,()=>{saveSelection(st);if(!st.source)sync(st);buttons(st)}));
    status(st);buttons(st);
  }
  function hideResize(st){const h=st.root.querySelector('.ff-resize');if(h)h.style.display='none'}
  function positionResize(st){const h=st.root.querySelector('.ff-resize'),img=st.selected;if(!h||!img)return hideResize(st);const r=img.getBoundingClientRect();h.style.left=r.right+'px';h.style.top=r.bottom+'px';h.style.display='block'}
  let drag=null;sections.addEventListener('pointerdown',e=>{const h=e.target.closest('.ff-resize');if(!h)return;const root=h.closest('[data-ff-editor]');const textarea=root?.parentElement?.querySelector('textarea[data-field="content"]');const st=textarea&&states.get(textarea);if(!st?.selected)return;e.preventDefault();const r=st.selected.getBoundingClientRect();drag={st,startX:e.clientX,startWidth:r.width,id:e.pointerId};h.setPointerCapture?.(e.pointerId)});sections.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const max=Math.max(120,drag.st.ed.clientWidth-24);const w=Math.max(80,Math.min(max,drag.startWidth+(e.clientX-drag.startX)));drag.st.selected.style.width=Math.round(w)+'px';drag.st.selected.style.maxWidth='100%';drag.st.selected.style.height='auto';positionResize(drag.st)});sections.addEventListener('pointerup',()=>{if(drag){sync(drag.st);drag=null}});sections.addEventListener('pointercancel',()=>drag=null);window.addEventListener('scroll',()=>allStates.forEach(st=>st.selected&&positionResize(st)),{passive:true});
  function enhance(){sections.querySelectorAll('.npb-section[data-type="rich_text"]').forEach(section=>{if(section.dataset.editorEnhanced==='1')return;const textarea=section.querySelector('textarea[data-field="content"]');if(!textarea)return;const root=document.importNode(template.content,true).firstElementChild;textarea.parentElement.appendChild(root);section.dataset.editorEnhanced='1';init(root,textarea)})}
  new MutationObserver(enhance).observe(sections,{childList:true,subtree:true});enhance();
})();
</script>
@endpush
