@php($brand = \App\Models\SystemSetting::query()->whereIn('key',['company.name','company.logo_path','company.tagline'])->pluck('value','key'))
@php($brandName = $brand->get('company.name') ?: config('fuelfree.company.name'))
@php($logoPath = $brand->get('company.logo_path'))
<style>
.header{position:sticky;top:0;z-index:50;background:rgba(2,10,16,.78);backdrop-filter:blur(20px);border-bottom:1px solid rgba(86,210,238,.15)}
.nav{height:70px;display:flex;align-items:center;justify-content:space-between;gap:15px}.brand{display:flex;align-items:center;gap:10px;font-weight:850;min-width:0;color:#effcff!important;text-decoration:none!important}.brand:visited,.brand:hover,.brand:active{color:#effcff!important;text-decoration:none!important}.brand img{width:40px;height:40px;object-fit:contain;border-radius:10px}.brand i{color:#43d1f0}.brand span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.menu{display:flex;gap:3px}.menu a,.menu a:visited{font-size:10px;color:#9bb5be!important;padding:10px;border-radius:9px;text-decoration:none!important}.menu a:hover,.menu a:active{color:#fff!important;background:rgba(67,209,240,.08);text-decoration:none!important}.menu-btn{display:none;width:42px;height:42px;border:1px solid rgba(86,210,238,.15);border-radius:11px;background:#06141d;color:#fff}
@media(max-width:720px){.menu-btn{display:grid;place-items:center}.menu{display:none;position:absolute;top:70px;left:12px;right:12px;flex-direction:column;padding:8px;background:rgba(4,18,26,.98);border:1px solid rgba(86,210,238,.15);border-radius:14px}.menu.open{display:flex}.menu a,.menu a:visited{padding:12px}}
</style>
<header class="header"><div class="shell nav"><a class="brand" href="{{ route('home') }}">@if($logoPath)<img src="{{ asset('storage/'.ltrim($logoPath,'/')) }}" alt="{{ $brandName }}">@else<i class="fa-solid fa-bolt"></i>@endif<span>{{ $brandName }}</span></a><button class="menu-btn" type="button" aria-label="Open navigation"><i class="fa-solid fa-bars"></i></button><nav class="menu"><a href="{{ route('home') }}">Home</a><a href="{{ route('site.about') }}">About Us</a><a href="{{ route('site.solutions') }}">Solutions</a><a href="{{ route('site.plants') }}">Plants</a><a href="{{ route('site.future-project') }}">Future Project</a><a href="{{ route('management') }}">Management Team</a><a href="{{ route('news.index') }}">News</a><a href="{{ route('site.career') }}">Career</a><a href="{{ route('contact') }}">Contact</a></nav></div></header>
<script>(function(){const b=document.querySelector('.menu-btn'),m=document.querySelector('.menu');if(b&&m&&!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>m.classList.toggle('open'))}})();</script>
