@php($brand = \App\Models\SystemSetting::query()->whereIn('key',['company.name','company.logo_path','company.tagline'])->pluck('value','key'))
@php($brandName = $brand->get('company.name') ?: config('fuelfree.company.name'))
@php($logoPath = $brand->get('company.logo_path'))
<style>
.header{position:sticky;top:0;z-index:50;background:rgba(3,16,24,.9);backdrop-filter:blur(16px);border-bottom:1px solid rgba(83,218,240,.16)}
.nav{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:15px}.brand{display:flex;align-items:center;gap:10px;font-weight:850;font-size:15px;min-width:0;color:#effcff!important;text-decoration:none!important}.brand:visited,.brand:hover,.brand:active{color:#effcff!important;text-decoration:none!important}.brand img{width:42px;height:42px;object-fit:contain;border-radius:9px}.brand i{color:#48d8f1}.brand-name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#effcff!important}.menu{display:flex;gap:3px}.menu a,.menu a:visited{font-size:10px;color:#a7c0c8!important;padding:10px 9px;border-radius:9px;text-decoration:none!important}.menu a:hover,.menu a:active{background:rgba(72,216,241,.08);color:#fff!important;text-decoration:none!important}.menu-btn{display:none;background:#071923;color:#fff;border:1px solid rgba(83,218,240,.16);border-radius:10px;padding:11px 13px}
@media(max-width:650px){.menu-btn{display:block}.menu{display:none;position:absolute;top:70px;left:12px;right:12px;padding:8px;flex-direction:column;background:#06131b;border:1px solid rgba(83,218,240,.16);border-radius:14px}.menu.open{display:flex}.menu a,.menu a:visited{padding:12px}.brand img{width:36px;height:36px}}
</style>
<header class="header"><div class="shell nav"><a class="brand" href="{{ route('home') }}">@if($logoPath)<img src="{{ asset('storage/'.ltrim($logoPath,'/')) }}" alt="{{ $brandName }}">@else<i class="fa-solid fa-bolt"></i>@endif<span class="brand-name">{{ $brandName }}</span></a><button class="menu-btn" type="button" aria-label="Open navigation">☰</button><nav class="menu"><a href="{{ route('site.about') }}">About Us</a><a href="{{ route('site.plants') }}">Plants</a><a href="{{ route('site.solutions') }}">Solutions</a><a href="{{ route('site.future-project') }}">Future Project</a><a href="{{ route('site.gallery') }}">Gallery</a><a href="{{ route('management') }}">Management</a><a href="{{ route('site.career') }}">Career</a><a href="{{ route('contact') }}">Contact</a></nav></div></header>
<script>(function(){const b=document.querySelector('.menu-btn'),m=document.querySelector('.menu');if(b&&m&&!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',()=>m.classList.toggle('open'))}})();</script>
