@extends('layouts.portal')
@section('title','Website Inquiries')
@section('content')
@php
    $statusLabels = ['new'=>'New','read'=>'Read','in_progress'=>'In progress','replied'=>'Replied','closed'=>'Closed'];
    $statusIcons = ['new'=>'fa-circle-dot','read'=>'fa-envelope-open','in_progress'=>'fa-spinner','replied'=>'fa-reply','closed'=>'fa-check'];
@endphp
<style>
.inq{--g:#35c46a;--g2:#1f9d50;--b:#20aee8;--ink:#eaf8ef;--muted:#88a6a0;--line:rgba(79,205,135,.16);--panel:rgba(5,27,21,.78);width:100%;min-width:0}
.inq *{box-sizing:border-box}.inq-hero{position:relative;display:flex;align-items:flex-end;justify-content:space-between;gap:24px;padding:clamp(18px,2.5vw,30px);margin-bottom:18px;border:1px solid var(--line);border-radius:22px;overflow:hidden;background:radial-gradient(circle at 8% 0,rgba(53,196,106,.15),transparent 38%),radial-gradient(circle at 92% 100%,rgba(32,174,232,.12),transparent 34%),linear-gradient(135deg,rgba(7,36,27,.92),rgba(3,20,25,.88));box-shadow:0 24px 60px rgba(0,0,0,.2)}
.inq-hero:after{content:"";position:absolute;inset:auto -10% -75%;height:180px;background:linear-gradient(90deg,transparent,rgba(53,196,106,.13),rgba(32,174,232,.1),transparent);filter:blur(28px);animation:inqGlow 7s ease-in-out infinite alternate}.inq-copy,.inq-total{position:relative;z-index:1}.inq .eyebrow{color:#65e494!important;letter-spacing:.16em}.inq h1{margin:7px 0 0;letter-spacing:-.04em}.inq-hero p{margin:9px 0 0;max-width:680px;color:#91aca6}.inq-total{display:flex;align-items:center;gap:10px;padding:11px 14px;border:1px solid rgba(79,205,135,.2);border-radius:14px;background:rgba(6,32,24,.72);white-space:nowrap;box-shadow:inset 0 1px rgba(255,255,255,.03)}.inq-total i{color:#50d77b}.inq-total strong{color:#f1fff5;font-size:18px}.inq-total span{color:#91aaa4;font-size:12px}
.inq-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px;padding:6px;border:1px solid var(--line);border-radius:15px;background:rgba(3,20,16,.72);backdrop-filter:blur(16px);overflow:hidden}.inq-filters{display:flex;gap:4px;min-width:0;overflow:auto;scrollbar-width:none}.inq-filters::-webkit-scrollbar{display:none}.inq-filter{display:inline-flex;align-items:center;gap:7px;min-height:40px;padding:8px 11px;border:1px solid transparent;border-radius:10px;color:#77948e;text-decoration:none;font-size:12px;font-weight:750;white-space:nowrap;transition:.2s ease}.inq-filter:hover{color:#dfffee;background:rgba(53,196,106,.07)}.inq-filter.active{color:#f2fff6;background:linear-gradient(135deg,rgba(53,196,106,.16),rgba(32,174,232,.08));border-color:rgba(79,205,135,.2);box-shadow:inset 0 0 0 1px rgba(255,255,255,.02)}.inq-filter.active i{color:#57df80}.inq-hint{padding:0 8px;color:#66827b;font-size:11px;white-space:nowrap}
.inq-card{border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,rgba(6,31,24,.86),rgba(3,19,24,.82));box-shadow:0 24px 65px rgba(0,0,0,.18);overflow:hidden}.inq-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid var(--line)}.inq-head strong{font-size:15px}.inq-head span{color:#6f8d86;font-size:11px}.inq-table-wrap{overflow-x:auto}.inq-table{width:100%;min-width:760px;border-collapse:collapse}.inq-table th{padding:11px 18px;text-align:left;border-bottom:1px solid var(--line);background:rgba(2,17,14,.36);color:#62847b;font-size:10px;letter-spacing:.1em;text-transform:uppercase}.inq-table td{padding:14px 18px;border-bottom:1px solid rgba(79,205,135,.08);vertical-align:middle;color:#c8ddd6}.inq-table tr:last-child td{border-bottom:0}.inq-table tbody tr{transition:.18s ease}.inq-table tbody tr:hover{background:rgba(53,196,106,.035)}.person{display:flex;align-items:center;gap:10px;min-width:190px}.avatar{width:38px;height:38px;display:grid;place-items:center;flex:0 0 38px;border:1px solid rgba(53,196,106,.2);border-radius:12px;background:linear-gradient(145deg,rgba(53,196,106,.14),rgba(32,174,232,.08));color:#6ee993;font-weight:800}.person-main{min-width:0}.name,.email,.subject{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.name{max-width:220px;color:#e8f8ef;font-weight:750}.email{max-width:220px;margin-top:3px;color:#718f88;font-size:11px}.subject{max-width:290px;color:#d8ebe4;font-weight:650}.phone{display:block;margin-top:4px;color:#628079;font-size:10px}.date{color:#94aaa4;font-size:11px;white-space:nowrap}.pill{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border:1px solid rgba(79,205,135,.14);border-radius:999px;background:rgba(79,205,135,.055);color:#b8d9ca;font-size:10px;font-weight:800;white-space:nowrap}.pill:before{content:"";width:6px;height:6px;border-radius:50%;background:#6e9285}.pill-new{color:#7feaa0;border-color:rgba(53,196,106,.2);background:rgba(53,196,106,.08)}.pill-new:before{background:#4cda78;box-shadow:0 0 0 3px rgba(76,218,120,.1)}.pill-in_progress{color:#78d7ee;border-color:rgba(32,174,232,.2);background:rgba(32,174,232,.07)}.pill-in_progress:before{background:#39b9ed}.pill-replied{color:#93e6a9}.pill-replied:before{background:#58d579}.pill-closed{color:#9aaba6}.view{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:36px;padding:7px 11px;border:1px solid rgba(53,196,106,.18);border-radius:9px;background:rgba(53,196,106,.055);color:#bcebd0;text-decoration:none;font-size:11px;font-weight:800;transition:.2s ease}.view:hover{color:#fff;background:linear-gradient(135deg,rgba(53,196,106,.14),rgba(32,174,232,.1));border-color:rgba(79,205,135,.32);transform:translateY(-1px)}
.empty{padding:56px 24px!important;text-align:center!important}.empty i{display:grid;place-items:center;width:48px;height:48px;margin:0 auto 12px;border:1px solid var(--line);border-radius:14px;background:rgba(53,196,106,.06);color:#57c978}.empty strong{display:block}.empty span{display:block;margin-top:5px;color:#6e8982;font-size:11px}.pagination{padding:15px 18px;border-top:1px solid var(--line)}.pagination nav{display:flex;justify-content:center}.pagination svg{width:16px;height:16px}
.mobile-list{display:none}
@media(max-width:900px){.inq-hero{align-items:flex-start;flex-direction:column;gap:15px;padding:20px}.inq-total{width:100%}.inq-toolbar{align-items:stretch;flex-direction:column}.inq-hint{display:none}.inq-table-wrap{display:none}.mobile-list{display:grid;gap:8px;padding:9px}.mobile-item{display:block;padding:13px;border:1px solid rgba(79,205,135,.11);border-radius:15px;background:rgba(3,20,16,.55);color:inherit;text-decoration:none;transition:.18s ease}.mobile-item:hover{border-color:rgba(79,205,135,.22);transform:translateY(-1px)}.mobile-top{display:flex;justify-content:space-between;gap:10px}.mobile-person{display:flex;gap:9px;min-width:0}.mobile-person .name{max-width:none}.mobile-person .email{max-width:calc(100vw - 190px)}.mobile-subject{margin:12px 0 10px;color:#e0f1ea;font-size:13px;font-weight:750;line-height:1.4}.mobile-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px;padding-top:9px;border-top:1px solid rgba(79,205,135,.08);color:#66827b;font-size:10px}.mobile-arrow{color:#55d77d}}
@media(max-width:520px){.inq h1{font-size:30px!important}.inq-hero p{font-size:14px!important}.inq-filter{min-height:42px;padding-inline:10px}.inq-card{border-radius:16px}.inq-head{padding:14px}.mobile-list{padding:7px}.mobile-item{padding:11px}.mobile-person .email{max-width:calc(100vw - 175px)}}
@media(prefers-reduced-motion:reduce){.inq *,.inq *:before,.inq *:after{animation:none!important;transition:none!important}}
@keyframes inqGlow{from{transform:translateX(-8%);opacity:.55}to{transform:translateX(8%);opacity:1}}
</style>
<div class="inq">
<section class="inq-hero"><div class="inq-copy"><div class="eyebrow">CLIENT COMMUNICATION</div><h1>Website Inquiries</h1><p>One simple inbox for messages received from the public website.</p></div><div class="inq-total"><i class="fa-solid fa-inbox"></i><strong>{{ $inquiries->total() }}</strong><span>{{ $inquiries->total() === 1 ? 'inquiry' : 'inquiries' }}</span></div></section>
<div class="inq-toolbar"><nav class="inq-filters" aria-label="Inquiry status filters">
<a class="inq-filter {{ $status === '' ? 'active' : '' }}" href="{{ route('admin.inquiries.index') }}"><i class="fa-solid fa-layer-group"></i>All</a>
@foreach(['new','read','in_progress','replied','closed'] as $key)<a class="inq-filter {{ $status === $key ? 'active' : '' }}" href="{{ route('admin.inquiries.index',['status'=>$key]) }}"><i class="fa-solid {{ $statusIcons[$key] }}"></i>{{ $statusLabels[$key] }}</a>@endforeach
</nav><span class="inq-hint"><i class="fa-regular fa-clock"></i> Latest first</span></div>
<section class="inq-card"><div class="inq-head"><strong>{{ $status ? ($statusLabels[$status] ?? 'Filtered') : 'All inquiries' }}</strong><span>{{ $inquiries->firstItem() ?? 0 }}–{{ $inquiries->lastItem() ?? 0 }} of {{ $inquiries->total() }}</span></div>
<div class="inq-table-wrap"><table class="inq-table"><thead><tr><th>Contact</th><th>Subject</th><th>Status</th><th>Received</th><th></th></tr></thead><tbody>
@forelse($inquiries as $inquiry)
@php $label=$statusLabels[$inquiry->status] ?? str_replace('_',' ',ucfirst($inquiry->status)); $initial=mb_strtoupper(mb_substr(trim($inquiry->name ?: $inquiry->email),0,1)); @endphp
<tr><td><div class="person"><span class="avatar">{{ $initial }}</span><div class="person-main"><span class="name">{{ $inquiry->name ?: 'Unknown sender' }}</span><span class="email">{{ $inquiry->email }}</span></div></div></td><td><span class="subject">{{ $inquiry->subject ?: 'No subject' }}</span>@if($inquiry->phone)<span class="phone"><i class="fa-solid fa-phone"></i> {{ $inquiry->phone }}</span>@endif</td><td><span class="pill pill-{{ $inquiry->status }}">{{ $label }}</span></td><td><span class="date">{{ $inquiry->created_at->format('d M Y') }}<br>{{ $inquiry->created_at->format('h:i A') }}</span></td><td><a class="view" href="{{ route('admin.inquiries.show',$inquiry) }}"><i class="fa-regular fa-eye"></i>View</a></td></tr>
@empty<tr><td colspan="5" class="empty"><i class="fa-regular fa-envelope"></i><strong>No inquiries found</strong><span>New website messages will appear here.</span></td></tr>@endforelse
</tbody></table></div>
<div class="mobile-list">@forelse($inquiries as $inquiry)@php $label=$statusLabels[$inquiry->status] ?? str_replace('_',' ',ucfirst($inquiry->status)); $initial=mb_strtoupper(mb_substr(trim($inquiry->name ?: $inquiry->email),0,1)); @endphp<a class="mobile-item" href="{{ route('admin.inquiries.show',$inquiry) }}"><div class="mobile-top"><div class="mobile-person"><span class="avatar">{{ $initial }}</span><div class="person-main"><span class="name">{{ $inquiry->name ?: 'Unknown sender' }}</span><span class="email">{{ $inquiry->email }}</span></div></div><span class="pill pill-{{ $inquiry->status }}">{{ $label }}</span></div><div class="mobile-subject">{{ $inquiry->subject ?: 'No subject' }}</div><div class="mobile-bottom"><span>{{ $inquiry->created_at->format('d M Y, h:i A') }}</span><span class="mobile-arrow"><i class="fa-solid fa-arrow-right"></i></span></div></a>@empty<div class="empty"><i class="fa-regular fa-envelope"></i><strong>No inquiries found</strong><span>New website messages will appear here.</span></div>@endforelse</div>
@if($inquiries->hasPages())<div class="pagination">{{ $inquiries->links() }}</div>@endif
</section></div>
@endsection
