@extends('layouts.portal')
@section('title','Theme Builder')
@section('content')
<section class="hero"><div><span class="eyebrow">DESIGN &amp; LAYOUT</span><h1>Theme Builder</h1><p>Set the global visual language of the website. These values are stored centrally for consistent frontend styling.</p></div><a class="back" href="{{route('admin.design.index',['area'=>'header'])}}">Design Builders →</a></section>
@if(session('status'))<div class="notice">{{session('status')}}</div>@endif @if($errors->any())<div class="errors">{{$errors->first()}}</div>@endif
<form method="POST" action="{{route('admin.theme.update')}}">@csrf
<div class="grid"><div class="card"><div class="head"><strong>Colors</strong><small>Global palette</small></div>@foreach(['primary'=>'Primary','accent'=>'Accent','background'=>'Background','surface'=>'Surface','text'=>'Text','muted'=>'Muted'] as $k=>$label)<label class="field"><span>{{$label}}</span><div class="color"><input type="color" name="{{$k}}" value="{{$theme[$k]}}"><input value="{{$theme[$k]}}" readonly></div></label>@endforeach</div>
<div class="card"><div class="head"><strong>Typography &amp; Layout</strong><small>Global sizing defaults</small></div><label class="field"><span>Maximum content width</span><input name="max_width" value="{{$theme['max_width']}}"></label><label class="field"><span>Component radius</span><input name="radius" value="{{$theme['radius']}}"></label><label class="field"><span>Base font stack</span><input name="base_font" value="{{$theme['base_font']}}"></label><div class="preview"><div class="dot"></div><div><b>Live style preview</b><small>Palette values are saved globally and can be consumed by public components.</small></div></div></div></div>
<div class="actions"><button class="primary">Save Theme</button></div></form>
@endsection
@push('styles')<style>
.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:22px}.eyebrow{font-size:9px;letter-spacing:.18em;color:#54cde8}.hero h1{margin:6px 0;font-size:clamp(28px,3.2vw,44px)}.hero p{margin:0;color:#7898a5;font-size:12px;line-height:1.65;max-width:700px}.back{font-size:10px;color:#9bc0ca;text-decoration:none}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{border:1px solid var(--line);border-radius:17px;background:linear-gradient(145deg,rgba(8,38,52,.84),rgba(3,21,30,.82));overflow:hidden}.head{padding:16px;border-bottom:1px solid var(--line)}.head strong{display:block;font-size:13px}.head small{display:block;color:#6f8e98;font-size:9px;margin-top:4px}.field{display:block;padding:12px 16px;border-bottom:1px solid rgba(104,204,235,.07)}.field>span{display:block;color:#a8c5cc;font-size:9px;margin-bottom:7px}.field>input{width:100%;padding:9px 10px;border:1px solid rgba(104,204,235,.15);border-radius:9px;background:#06151d;color:#dff4f7;font-size:10px;outline:0}.color{display:flex;gap:8px}.color input[type=color]{width:40px;height:34px;padding:2px;border-radius:8px;border:1px solid rgba(104,204,235,.15);background:#06151d}.color input[readonly]{flex:1}.preview{display:flex;gap:12px;margin:16px;padding:14px;border:1px dashed rgba(104,204,235,.18);border-radius:12px}.dot{width:36px;height:36px;border-radius:50%;background:var(--cyan,#48d8f1);box-shadow:0 0 22px rgba(72,216,241,.2)}.preview b{display:block;font-size:10px}.preview small{display:block;color:#718f99;font-size:8px;line-height:1.5;margin-top:3px}.actions{display:flex;justify-content:flex-end;margin-top:16px}.primary{border:0;border-radius:10px;padding:11px 16px;background:#1687a4;color:#fff;font-size:10px;font-weight:800;cursor:pointer}@media(max-width:700px){.hero{display:block}.back{display:inline-block;margin-top:12px}.grid{grid-template-columns:1fr}}
</style>@endpush