@extends('layouts.portal')
@section('title','Website Control Center')
@section('content')
<section class="hero"><div><span class="eyebrow">CLIENT WEBSITE CONTROL CENTER</span><h1>Manage the whole website.</h1><p>One place for content, projects, news, media, announcements and public website settings.</p></div></section>
<div class="stats"><article><i class="fa-solid fa-globe"></i><small>Website content</small><strong>{{ $contentTotal }}</strong><span>{{ $published }} published · {{ $drafts }} drafts</span></article><article><i class="fa-solid fa-industry"></i><small>Power projects</small><strong>{{ $plants }}</strong><span>Manage plants &amp; performance</span></article><article><i class="fa-solid fa-bullhorn"></i><small>Announcement banners</small><strong>{{ $popups }}</strong><span>Homepage popup controls</span></article><article><i class="fa-solid fa-users"></i><small>Admin users</small><strong>{{ $users }}</strong><span>Permission-aware accounts</span></article></div>
<section class="section"><div class="section-head"><div><span class="eyebrow">WEBSITE</span><h2>Everything the client manages</h2></div><p>Technical modules stay out of the way. Start with the public website areas that clients update regularly.</p></div><div class="control-grid">
<a href="{{ route('admin.site-content.index',['type'=>'company']) }}" class="control"><span><i class="fa-solid fa-building"></i></span><div><strong>Company &amp; About</strong><small>History, vision, mission, values and corporate messages</small></div><i class="fa-solid fa-arrow-right"></i></a>
<a href="{{ route('admin.site-content.index',['type'=>'management']) }}" class="control"><span><i class="fa-solid fa-people-group"></i></span><div><strong>Management</strong><small>Team profiles, photos, designations and ordering</small></div><b>{{ $management }}</b></a>
<a href="{{ route('admin.site-content.index',['type'=>'news']) }}" class="control"><span><i class="fa-solid fa-newspaper"></i></span><div><strong>News &amp; Notices</strong><small>Rich editor, images, video and social embeds</small></div><b>{{ $news }}</b></a>
<a href="{{ route('admin.site-popups.index') }}" class="control"><span><i class="fa-solid fa-image"></i></span><div><strong>Homepage Highlights</strong><small>Important image banners, timer or visitor close</small></div><b>{{ $popups }}</b></a>
<a href="{{ route('admin.plants.index') }}" class="control"><span><i class="fa-solid fa-bolt"></i></span><div><strong>Power Plants &amp; Projects</strong><small>Facilities, technical data and performance records</small></div><b>{{ $plants }}</b></a>
<a href="{{ route('admin.site-content.index',['type'=>'resource']) }}" class="control"><span><i class="fa-solid fa-folder-open"></i></span><div><strong>Resources &amp; Downloads</strong><small>Public reports, brochures, notices and documents</small></div><b>{{ $resources }}</b></a>
<a href="{{ route('admin.site-content.index',['type'=>'gallery']) }}" class="control"><span><i class="fa-solid fa-images"></i></span><div><strong>Gallery &amp; Media</strong><small>Photos, albums and public media content</small></div><b>{{ $gallery }}</b></a>
<a href="{{ route('admin.site-content.index',['type'=>'sustainability']) }}" class="control"><span><i class="fa-solid fa-leaf"></i></span><div><strong>Sustainability</strong><small>Approved energy and environmental content</small></div><b>{{ $sustainability }}</b></a>
<a href="{{ route('admin.settings') }}" class="control"><span><i class="fa-solid fa-sliders"></i></span><div><strong>Website Settings</strong><small>Logo, company name, tagline and public identity</small></div><i class="fa-solid fa-arrow-right"></i></a>
<a href="{{ route('admin.site-content.create') }}" class="control primary"><span><i class="fa-solid fa-plus"></i></span><div><strong>Create content</strong><small>Start a new page, news item, notice or section</small></div><i class="fa-solid fa-arrow-right"></i></a>
</div></section>
<section class="section"><div class="notice-panel"><i class="fa-solid fa-circle-info"></i><div><strong>Client-first publishing</strong><p>Drafts stay private. Published content flows from the dashboard database to the public website. No developer code changes are required for normal content updates.</p></div></div></section>
@endsection
@push('styles')<style>.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.stats article{padding:19px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,rgba(9,38,54,.86),rgba(5,22,32,.9));min-width:0}.stats i{font-size:17px;color:#5fd5ef}.stats small{display:block;margin-top:13px;color:#7396a4;text-transform:uppercase;letter-spacing:.1em;font-size:9px}.stats strong{display:block;font-size:27px;margin:7px 0}.stats span{color:#6f909c;font-size:9px}.section{margin-top:25px}.section-head{display:flex;justify-content:space-between;gap:25px;align-items:end;margin-bottom:15px}.section-head h2{font-size:21px;margin:6px 0}.section-head p{max-width:560px;color:#7898a5;font-size:11px;line-height:1.6}.control-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.control{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.025);color:#dceef2;text-decoration:none;transition:.2s}.control:hover{transform:translateY(-2px);border-color:rgba(91,214,239,.32);background:rgba(67,194,229,.06)}.control>span{width:42px;height:42px;flex:0 0 42px;display:grid;place-items:center;border-radius:12px;color:#64d8f2;background:rgba(67,194,229,.08);border:1px solid rgba(104,204,235,.13)}.control div{min-width:0;flex:1}.control strong{display:block;font-size:12px}.control small{display:block;margin-top:4px;color:#708f9b;font-size:9px;line-height:1.45}.control>b,.control>i:last-child{color:#72d9ee;font-size:11px}.control.primary{border-color:rgba(67,194,229,.25);background:linear-gradient(135deg,rgba(67,194,229,.12),rgba(67,194,229,.03))}.notice-panel{display:flex;gap:13px;padding:17px;border:1px solid rgba(67,194,229,.16);border-radius:16px;background:rgba(67,194,229,.045);color:#8fb1bc}.notice-panel>i{color:#5fd5ef;font-size:18px}.notice-panel strong{color:#d8edf2;font-size:12px}.notice-panel p{margin:6px 0 0;color:#7898a5;font-size:10px;line-height:1.6}@media(max-width:850px){.stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.stats,.control-grid{grid-template-columns:1fr}.section-head{display:block}.section-head p{margin-bottom:0}}</style>@endpush
