@extends('layouts.portal')
@section('title','Overview')
@section('content')
<section class="hero"><span class="eyebrow">WEBSITE CONTROL CENTER</span><h1>Good to see you.</h1><p>A focused overview of the parts that actually power the public FuelFree PowerPlant website—content, homepage media, inquiries and careers.</p></section>
<section class="stats">
<article><i class="fa-solid fa-globe"></i><small>Website content</small><strong>{{ $contentTotal }}</strong><span>{{ $published }} published · {{ $drafts }} drafts</span></article>
<article><i class="fa-solid fa-panorama"></i><small>Homepage sliders</small><strong>{{ $sliders }}</strong><span>Rotating homepage slides</span></article>
<article><i class="fa-solid fa-newspaper"></i><small>News &amp; notices</small><strong>{{ $news }}</strong><span>Public updates</span></article>
<article><i class="fa-solid fa-images"></i><small>Gallery albums</small><strong>{{ $gallery }}</strong><span>Public photo collections</span></article>
</section>
<section class="overview-grid">
<article class="panel"><div class="panel-head"><div><span class="eyebrow">PUBLIC WEBSITE</span><h2>Content at a glance</h2></div><i class="fa-solid fa-layer-group"></i></div><div class="rows"><div><span>Company sections</span><strong>{{ $company }}</strong></div><div><span>News &amp; notices</span><strong>{{ $news }}</strong></div><div><span>Gallery albums</span><strong>{{ $gallery }}</strong></div><div><span>Homepage highlights</span><strong>{{ $popups }}</strong></div></div></article>
<article class="panel"><div class="panel-head"><div><span class="eyebrow">INBOX &amp; CAREER</span><h2>Items needing attention</h2></div><i class="fa-solid fa-inbox"></i></div><div class="rows"><div><span>Website inquiries</span><strong>{{ $inquiries }}</strong></div><div><span>Career applications</span><strong>{{ $applications }}</strong></div><div><span>New applications</span><strong>{{ $newApplications }}</strong></div><div><span>Published content</span><strong>{{ $published }}</strong></div></div></article>
</section>
<section class="actions"><a href="{{ route('admin.sliders.index') }}"><i class="fa-solid fa-panorama"></i><span><small>Homepage</small><strong>Manage Slider</strong></span></a><a href="{{ route('admin.site-content.index',['type'=>'news']) }}"><i class="fa-solid fa-newspaper"></i><span><small>Website</small><strong>Manage News</strong></span></a><a href="{{ route('admin.gallery.index') }}"><i class="fa-solid fa-images"></i><span><small>Website</small><strong>Manage Gallery</strong></span></a>@if(auth()->user()->hasPermission('career.view'))<a href="{{ route('admin.career-applications.index') }}"><i class="fa-solid fa-briefcase"></i><span><small>Recruitment</small><strong>Career Applications</strong></span></a>@endif</section>
@endsection
@push('styles')<style>.hero{padding:8px 0 24px}.hero h1{font-size:clamp(30px,4vw,48px);margin:8px 0}.hero p{color:#7898a5;font-size:11px;line-height:1.7;max-width:760px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.stats article,.panel,.actions a{border:1px solid var(--line);background:linear-gradient(145deg,rgba(9,38,54,.86),rgba(5,22,32,.9));border-radius:18px}.stats article{padding:19px}.stats i,.panel-head>i,.actions i{font-size:17px;color:#5fd5ef}.stats small{display:block;margin-top:13px;color:#7396a4;text-transform:uppercase;letter-spacing:.1em;font-size:9px}.stats strong{display:block;font-size:27px;margin:7px 0}.stats span{color:#6f909c;font-size:9px}.overview-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:13px}.panel{padding:21px}.panel-head{display:flex;justify-content:space-between;gap:15px}.panel-head h2{font-size:17px;margin:6px 0}.rows{margin-top:14px}.rows div{display:flex;align-items:center;justify-content:space-between;padding:13px 0;border-top:1px solid rgba(255,255,255,.055);font-size:10px;color:#7898a5}.rows strong{font-size:15px;color:#d9eef3}.actions{display:grid;grid-template-columns:repeat(4,1fr);gap:13px;margin-top:13px}.actions a{display:flex;align-items:center;gap:12px;padding:17px;color:inherit;text-decoration:none}.actions a:hover{border-color:rgba(95,213,239,.3);transform:translateY(-1px)}.actions small,.actions strong{display:block}.actions small{font-size:8px;color:#6f909c}.actions strong{font-size:11px;margin-top:4px}@media(max-width:850px){.stats{grid-template-columns:repeat(2,1fr)}.actions{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.stats,.overview-grid,.actions{grid-template-columns:1fr}.hero{padding-top:4px}.panel{padding:16px}.stats article{padding:16px}}</style>@endpush