@extends('layouts.portal')
@section('title','System Settings')
@section('content')
<section class="hero"><div class="eyebrow">PLATFORM CONFIGURATION</div><h1>System Settings</h1><p>Manage company identity, storage and energy-data integration.</p></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="form-card"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.settings.update') }}">@csrf
<div class="identity"><div class="logo-preview">@if($settings['company.logo_path'])<img src="{{ asset('storage/'.$settings['company.logo_path']) }}" alt="Company logo">@else<i class="fa-solid fa-building"></i>@endif</div><div><div class="eyebrow">BRAND IDENTITY</div><strong>{{ $settings['company.name'] }}</strong><span>Logo and company identity are shared with the public website.</span><label class="upload"> <i class="fa-solid fa-cloud-arrow-up"></i> Change logo<input type="file" name="company[logo]" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label></div></div>
<div class="fields"><div><label>Company name</label><input name="company[name]" value="{{ old('company.name',$settings['company.name']) }}" required maxlength="150"></div><div><label>Company domain</label><input name="company[domain]" value="{{ old('company.domain',$settings['company.domain']) }}" required maxlength="255"></div><div class="full"><label>Tagline</label><input name="company[tagline]" value="{{ old('company.tagline',$settings['company.tagline']) }}" maxlength="255"></div><div><label>Timezone</label><input name="company[timezone]" value="{{ old('company.timezone',$settings['company.timezone']) }}" required placeholder="Asia/Dhaka"></div><div><label>Storage quota (GiB)</label><input name="storage[quota_gib]" type="number" min="1" step="1" value="{{ old('storage.quota_gib',$settings['storage.quota_gib']) }}" required></div><div class="full toggle-card"><div><strong>Real energy data integration</strong><span>Keep disabled until an approved plant data source is configured and tested.</span></div><label class="switch"><input type="checkbox" name="energy[real_data_enabled]" value="1" {{ old('energy.real_data_enabled',$settings['energy.real_data_enabled']) === '1' ? 'checked' : '' }}><i></i></label></div></div><div class="actions"><button type="submit"><i class="fa-solid fa-floppy-disk"></i> Save settings</button></div></form></div>
@endsection
@push('styles')<style>.form-card{max-width:900px;background:rgba(255,255,255,.025);border:1px solid var(--line);border-radius:20px;padding:22px}.identity{display:flex;align-items:center;gap:15px;padding:16px;margin-bottom:20px;border:1px solid rgba(76,205,233,.13);border-radius:16px;background:linear-gradient(135deg,rgba(76,205,233,.06),rgba(255,255,255,.015))}.logo-preview{width:68px;height:68px;flex:none;border-radius:17px;display:grid;place-items:center;overflow:hidden;border:1px solid var(--line);background:#061923;color:#62d4ed;font-size:25px}.logo-preview img{width:100%;height:100%;object-fit:contain}.identity strong{display:block;color:#e4f5f8;font-size:15px;margin:4px 0}.identity span{display:block;color:#7899a5;font-size:9px}.upload{display:inline-flex;align-items:center;gap:7px;margin-top:9px!important;padding:8px 10px;border:1px solid var(--line);border-radius:9px;color:#9ed3df!important;cursor:pointer!important}.upload input{display:none!important}.fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}.full{grid-column:1/-1}label{display:block;font-size:10px;color:#9eb9c4;margin:0 0 7px}input:not([type=checkbox]){width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid var(--line);background:#071c29;color:#e9f7fb;outline:none}.toggle-card{display:flex;justify-content:space-between;align-items:center;gap:18px;padding:15px;border:1px solid rgba(76,205,233,.12);border-radius:14px;background:rgba(76,205,233,.035)}.toggle-card strong{display:block;color:#d8edf2;font-size:12px}.toggle-card span{display:block;color:#6f919d;font-size:9px;margin-top:5px}.switch{position:relative;width:48px;height:28px;margin:0;flex:none}.switch input{opacity:0;width:0;height:0}.switch i{position:absolute;inset:0;border-radius:99px;background:#173442;transition:.2s;cursor:pointer}.switch i:before{content:'';position:absolute;width:20px;height:20px;left:4px;top:4px;border-radius:50%;background:#9bb5bd;transition:.2s}.switch input:checked+i{background:#219fc2}.switch input:checked+i:before{transform:translateX(20px);background:#fff}.actions{display:flex;justify-content:flex-end;margin-top:22px}.actions button{border:0;border-radius:11px;padding:12px 17px;background:#31afd2;color:#fff;font-weight:700}.notice{padding:12px 14px;border-radius:12px;margin-bottom:14px;background:rgba(67,194,137,.1);border:1px solid rgba(67,194,137,.2);color:#a8e5ca}.errors{padding:11px;border-radius:10px;margin-bottom:16px;background:rgba(210,65,65,.12);color:#ffb0b0}@media(max-width:650px){.fields{grid-template-columns:1fr}.full{grid-column:auto}.identity{align-items:flex-start}.actions button{width:100%}}</style>@endpush
