@extends('layouts.portal')
@section('title','SEO Setup Help')
@section('content')
<section class="seo-help-head"><span class="eyebrow">SEO &amp; INTEGRATIONS · HELP</span><h1>Setup Help</h1><p>Follow these guides to obtain each value and verify that the configuration is working.</p><a href="{{ route('admin.settings.seo') }}"><i class="fa-solid fa-arrow-left"></i> Back to SEO settings</a></section>
<div class="help-grid">
<article class="help-card"><span class="eyebrow">GOOGLE SEARCH CONSOLE</span><h2>Verification</h2><ol><li>Open Google Search Console and add your website property.</li><li>Choose the HTML tag verification method.</li><li>Copy only the value inside the <code>content</code> attribute.</li><li>Paste it into <strong>Google Search Console verification</strong> in SEO settings and save.</li><li>Return to Search Console and click Verify.</li></ol><p class="tip">Do not paste the full HTML tag; this field stores only its content value.</p></article>
<article class="help-card"><span class="eyebrow">BING WEBMASTER</span><h2>Verification</h2><ol><li>Open Bing Webmaster Tools and add your site.</li><li>Select the HTML meta tag verification option.</li><li>Copy the verification content value supplied by Bing.</li><li>Paste it into <strong>Bing Webmaster verification</strong> and save.</li><li>Complete verification in Bing Webmaster Tools.</li></ol><p class="tip">The verification value is intended to appear publicly in your site's head.</p></article>
<article class="help-card"><span class="eyebrow">META</span><h2>Domain verification</h2><ol><li>Open Meta Business settings and select your domain.</li><li>Choose the meta-tag verification method when available.</li><li>Copy the verification content value.</li><li>Paste it into <strong>Meta domain verification</strong> and save.</li><li>Return to Meta and complete verification.</li></ol><p class="tip">This is optional and should only be configured when your organization uses Meta domain verification.</p></article>
<article class="help-card"><span class="eyebrow">GOOGLE ANALYTICS 4</span><h2>Measurement ID</h2><ol><li>Open Google Analytics and select the required GA4 property.</li><li>Open the Web data stream for this website.</li><li>Find the Measurement ID, normally beginning with <code>G-</code>.</li><li>Paste the complete ID into <strong>GA4 Measurement ID</strong>.</li><li>Save and verify traffic using the Realtime report.</li></ol><p class="tip">A Measurement ID identifies the web data stream; never paste a Google account password here.</p></article>
<article class="help-card"><span class="eyebrow">INDEXNOW</span><h2>API key</h2><ol><li>Generate a unique IndexNow key for this website.</li><li>Paste the key into <strong>IndexNow API key</strong> and save.</li><li>After saving, this system exposes the verification key at <code>/indexnow/{key}.txt</code> on the public website.</li><li>Use that exact key location when submitting URLs through an IndexNow-compatible service.</li><li>Confirm acceptance using the provider's submission or diagnostic tools.</li></ol><p class="tip">The IndexNow verification key is intentionally public. Never use a password or unrelated private API secret.</p></article>
<article class="help-card security"><span class="eyebrow">SECURITY</span><h2>What belongs here?</h2><p>Use these fields for identifiers and verification values intended for website integration. Never paste passwords, database credentials, private OAuth secrets, or unrelated service credentials.</p><p>If a future integration requires a genuinely secret API credential, it should use encrypted server-side storage and must never be printed into public HTML.</p></article>
</div>
@endsection
@push('styles')<style>.seo-help-head{max-width:1000px;margin-bottom:20px}.seo-help-head h1{margin:6px 0;color:#eaf8fb;font-size:clamp(30px,3.1vw,42px);letter-spacing:-.045em}.seo-help-head p{color:#7899a5;font-size:10px}.seo-help-head>a{display:inline-flex;gap:7px;margin-top:8px;color:#9ed3df;text-decoration:none;font-size:9px}.eyebrow{font-size:8px;letter-spacing:.16em;font-weight:800;color:#4dcde8}.help-grid{max-width:1120px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.help-card{padding:20px;border:1px solid rgba(76,205,233,.13);border-radius:17px;background:rgba(5,25,35,.72)}.help-card h2{margin:6px 0 12px;color:#eaf8fb;font-size:18px}.help-card ol{margin:0;padding-left:18px;color:#9eb9c4;font-size:9px;line-height:1.75}.help-card code{padding:2px 4px;border-radius:4px;background:rgba(72,216,241,.07);color:#bcecf5}.help-card .tip{margin:12px 0 0;padding-top:10px;border-top:1px solid rgba(104,204,235,.08);color:#668591;font-size:8px;line-height:1.6}.security{grid-column:1/-1}@media(max-width:700px){.help-grid{grid-template-columns:1fr}.help-card{padding:15px}.security{grid-column:auto}}</style>@endpush
