@extends('layouts.admin')
@section('title','Theme Builder')
@section('content')
<x-admin.page-header title="Theme Builder" eyebrow="APPEARANCE" description="One global visual policy for the public website." :actions="'<a class="admin-btn" href="'.route('admin.settings').'">Settings</a>'" />
@if(session('status'))<div class="admin-card" style="margin-bottom:16px"><div class="admin-card__body">{{ session('status') }}</div></div>@endif
@if($errors->any())<div class="admin-card" style="margin-bottom:16px"><div class="admin-card__body">{{ $errors->first() }}</div></div>@endif
<form method="POST" action="{{ route('admin.settings.theme.update') }}">@csrf
<x-admin.card><x-slot:header>Global color tokens</x-slot:header>
<div class="theme-grid">
@foreach(['theme.primary'=>'Primary','theme.secondary'=>'Secondary','theme.accent'=>'Accent','theme.surface'=>'Surface','theme.text'=>'Text','theme.muted'=>'Muted'] as $key=>$label)
<x-admin.setting-field :label="$label" :id="'theme-'.str_replace('.','-',$key)"><div class="color-row"><input type="color" name="{{ $key }}" value="{{ old($key,$settings[$key]) }}" aria-label="{{ $label }}"><input class="admin-input" value="{{ old($key,$settings[$key]) }}" readonly></div></x-admin.setting-field>
@endforeach
</div>
<x-admin.setting-field label="Global border radius" id="theme-radius"><input class="admin-input" type="number" min="0" max="32" name="theme.radius" value="{{ old('theme.radius',$settings['theme.radius']) }}"></x-admin.setting-field>
<div class="theme-grid">
<x-admin.setting-field label="Body font" id="theme-font-body"><input class="admin-input" name="theme.font_body" maxlength="120" value="{{ old('theme.font_body',$settings['theme.font_body']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Heading font" id="theme-font-heading"><input class="admin-input" name="theme.font_heading" maxlength="120" value="{{ old('theme.font_heading',$settings['theme.font_heading']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Base font size (px)" id="theme-base-size"><input class="admin-input" type="number" min="12" max="22" name="theme.base_size" value="{{ old('theme.base_size',$settings['theme.base_size']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Line height" id="theme-line-height"><input class="admin-input" type="number" min="1.1" max="2.2" step="0.1" name="theme.line_height" value="{{ old('theme.line_height',$settings['theme.line_height']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Section spacing (px)" id="theme-section-space"><input class="admin-input" type="number" min="0" max="160" name="theme.space_section" value="{{ old('theme.space_section',$settings['theme.space_section']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Content spacing (px)" id="theme-content-space"><input class="admin-input" type="number" min="0" max="80" name="theme.space_content" value="{{ old('theme.space_content',$settings['theme.space_content']) }}"></x-admin.setting-field>
</div>
<div style="margin-top:18px;border-top:1px solid var(--admin-border);padding-top:18px"><div style="font-size:11px;font-weight:700;margin-bottom:10px">Component tokens</div><div class="theme-grid">
<x-admin.setting-field label="Card padding (px)" id="theme-card-padding"><input class="admin-input" type="number" min="8" max="64" name="theme.card_padding" value="{{ old('theme.card_padding',$settings['theme.card_padding']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Button radius (px)" id="theme-button-radius"><input class="admin-input" type="number" min="0" max="32" name="theme.button_radius" value="{{ old('theme.button_radius',$settings['theme.button_radius']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Button height (px)" id="theme-button-height"><input class="admin-input" type="number" min="28" max="64" name="theme.button_height" value="{{ old('theme.button_height',$settings['theme.button_height']) }}"></x-admin.setting-field>
<x-admin.setting-field label="Input radius (px)" id="theme-input-radius"><input class="admin-input" type="number" min="0" max="32" name="theme.input_radius" value="{{ old('theme.input_radius',$settings['theme.input_radius']) }}"></x-admin.setting-field>
</div></div><div class="theme-preview" aria-label="Theme live preview"><div class="preview-head"><span>Live preview</span><small>Unsaved changes only</small></div><div class="preview-surface"><div class="preview-card"><h3 id="preview-heading">FuelFreePowerPlant</h3><p id="preview-text">A clean global design system preview. Changes here are not saved until you press Save Theme.</p><button type="button" id="preview-button">Get started</button><input id="preview-input" placeholder="Preview input" readonly></div></div></div><div style="display:flex;justify-content:flex-end;margin-top:18px"><button class="admin-btn admin-btn--primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save Theme</button></div>
</x-admin.card></form>
@push('head')<style>.theme-preview{margin-top:18px;border:1px solid var(--admin-border);border-radius:12px;overflow:hidden}.preview-head{display:flex;justify-content:space-between;gap:10px;padding:10px 12px;border-bottom:1px solid var(--admin-border);font-size:11px;font-weight:700}.preview-head small{font-size:9px;color:var(--admin-muted);font-weight:400}.preview-surface{padding:24px;background:#020a10}.preview-card{max-width:520px;padding:var(--pv-card-padding,24px);border:1px solid rgba(96,216,239,.16);border-radius:var(--pv-radius,12px);background:var(--pv-surface,#07131a);color:var(--pv-text,#eaf7fb)}.preview-card h3{margin:0 0 10px;font-size:22px;font-family:var(--pv-heading,Inter,sans-serif)}.preview-card p{margin:0 0 18px;color:var(--pv-muted,#8ea8b2);font:var(--pv-base,16px)/var(--pv-line,1.6) var(--pv-body,Inter,sans-serif)}#preview-button{height:var(--pv-button-height,42px);padding:0 16px;border:0;border-radius:var(--pv-button-radius,10px);background:var(--pv-primary,#55cce7);color:#041017;font-weight:700;cursor:pointer}#preview-input{display:block;width:100%;box-sizing:border-box;height:var(--pv-button-height,42px);margin-top:12px;padding:0 12px;border:1px solid rgba(96,216,239,.22);border-radius:var(--pv-input-radius,10px);background:transparent;color:inherit}.theme-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.color-row{display:flex;gap:8px}.color-row input[type=color]{width:42px;height:38px;padding:3px;border:1px solid var(--admin-border);border-radius:9px;background:transparent}.admin-input{width:100%;box-sizing:border-box;min-height:38px;padding:8px 11px;border:1px solid var(--admin-border);border-radius:10px;background:rgba(255,255,255,.035);color:var(--admin-text);font:inherit}@media(max-width:800px){.theme-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.theme-grid{grid-template-columns:1fr}}</style><script>
(function(){const q=s=>document.querySelector(s), f=document.querySelector('form'), root=q('.preview-card'); if(!f||!root)return;
const map={'theme.primary':'--pv-primary','theme.surface':'--pv-surface','theme.text':'--pv-text','theme.muted':'--pv-muted','theme.radius':'--pv-radius','theme.font_body':'--pv-body','theme.font_heading':'--pv-heading','theme.base_size':'--pv-base','theme.line_height':'--pv-line','theme.card_padding':'--pv-card-padding','theme.button_radius':'--pv-button-radius','theme.button_height':'--pv-button-height','theme.input_radius':'--pv-input-radius'};
function sync(){Object.entries(map).forEach(([name,token])=>{const el=f.querySelector('[name="'+name+'"]');if(el)root.style.setProperty(token,(el.type==='color'?el.value:el.value+( /radius|padding|height|base/.test(name)?'px':'')));});}
f.querySelectorAll('input').forEach(el=>el.addEventListener('input',sync)); sync();})();
</script>@endpush
@endsection