@extends('layouts.portal')
@section('title','Email Management')
@section('content')
<section class="hero"><div class="eyebrow">ADMIN MAIL SERVICES</div><h1>Mail Accounts</h1><p>Administrators create and manage the organisation's mail accounts here. Users access their mailbox separately through the dedicated mail service.</p></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="toolbar"><a class="webmail-action" href="{{ config('cpanel.webmail_url','https://mail.fuelfreepowerplant.com') }}" target="_blank" rel="noopener"><i class="fa-solid fa-envelope-open-text"></i> Open Mail Portal</a>@if(auth()->user()->hasPermission('email.manage'))<a class="action" href="{{ route('admin.email.create') }}"><i class="fa-solid fa-plus"></i> Create mail account</a>@endif</div>
<div class="mail-note"><i class="fa-solid fa-circle-info"></i><span><strong>Separation of responsibilities:</strong> mail accounts are provisioned by administrators only. The mailbox experience lives at <b>mail.fuelfreepowerplant.com</b>; it is not part of the public website navigation.</span></div>
<div class="table-card"><div class="table-wrap"><table><thead><tr><th>Mail account</th><th>Owner</th><th>Provisioning</th><th>Status</th><th>Server connection</th><th>Actions</th></tr></thead><tbody>@forelse($accounts as $account)<tr><td><strong>{{ $account->address }}</strong><small>{{ $account->display_name ?: 'No display name' }}</small></td><td>{{ $account->user->name }}</td><td><span class="badge {{ $account->provisioned ? 'ok' : 'pending' }}">{{ $account->provisioned ? 'Created on server' : 'Record only' }}</span><small>{{ $account->provider_message }}</small></td><td>{{ ucfirst($account->status) }}</td><td><div><b>IMAP</b> {{ $account->imap_host ?: '—' }}:{{ $account->imap_port }}</div><div><b>SMTP</b> {{ $account->smtp_host ?: '—' }}:{{ $account->smtp_port }}</div><small>Username: {{ $account->username ?: $account->address }}</small></td><td>@if(auth()->user()->hasPermission('email.manage'))<form method="POST" action="{{ route('admin.email.destroy',$account) }}" onsubmit="return confirm('This will remove the mail account from the hosting server and delete its local record. Continue?')">@csrf @method('DELETE')<button class="danger"><i class="fa-solid fa-trash-can"></i> Delete</button></form>@endif</td></tr>@empty<tr><td colspan="6">No mail accounts have been created yet.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $accounts->links() }}</div></div>
@endsection
@push('styles')<style>.toolbar{display:flex;justify-content:flex-end;align-items:center;gap:9px;flex-wrap:wrap;margin-bottom:14px}.action,.webmail-action{display:inline-flex;align-items:center;gap:8px;padding:11px 15px;border-radius:11px;color:#fff;text-decoration:none;font-weight:700;font-size:13px}.action{background:#31afd2}.webmail-action{background:rgba(69,200,232,.08);border:1px solid rgba(69,200,232,.2);color:#9fe9fa}.notice,.errors,.mail-note{padding:12px 14px;border-radius:12px;margin-bottom:14px}.notice{background:rgba(67,194,137,.1);border:1px solid rgba(67,194,137,.2);color:#a8e5ca}.errors{background:rgba(210,65,65,.12);color:#ffb0b0}.mail-note{display:flex;gap:10px;align-items:flex-start;background:rgba(69,200,232,.045);border:1px solid rgba(69,200,232,.12);color:#91b3be;font-size:12px;line-height:1.6}.mail-note i{color:#58d4ee;margin-top:2px}.mail-note strong,.mail-note b{color:#d8f7fc}.table-card{background:rgba(255,255,255,.025);border:1px solid var(--line);border-radius:18px;overflow:hidden}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:980px}th,td{text-align:left;padding:14px 16px;border-bottom:1px solid rgba(255,255,255,.06);font-size:12px;vertical-align:top}th{color:#74cce9;font-size:10px;text-transform:uppercase;letter-spacing:.08em}td{color:#b5cbd4}td small{display:block;color:#718f9d;margin-top:4px;line-height:1.5}.badge{display:inline-block;padding:5px 8px;border-radius:999px;font-size:10px}.badge.ok{background:rgba(67,194,137,.12);color:#8fe1bb}.badge.pending{background:rgba(230,170,55,.12);color:#f0ce8a}.danger{border:0;background:transparent;color:#ff9eaa;cursor:pointer;padding:0;font:inherit}.pagination{padding:12px}</style>@endpush
