@extends('layouts.portal')
@section('title','Create Mailbox')
@section('content')
<section class="hero"><div class="eyebrow">MANAGED EMAIL</div><h1>Create mailbox</h1><p>Create a real hosting mailbox from the control center. There is no application-level mailbox count limit; the hosting account controls the actual allowance.</p></section>
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
@if($cpanelConfigured)<div class="notice">cPanel provisioning is connected. New mailboxes will be created on the hosting server with an unlimited mailbox quota.</div>@else<div class="warning">cPanel provisioning is not configured yet. This form can save mailbox records, but a real mailbox will not be created until the cPanel API settings are added to <code>.env</code>.</div>@endif
<div class="form-card"><form method="POST" action="{{ route('admin.email.store') }}">@csrf<div class="fields">
<div><label>Owner</label><select name="user_id" required>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('user_id') == $user->id)>{{ $user->name }} — {{ $user->email }}</option>@endforeach</select></div>
<div><label>Mailbox address</label><input type="email" name="address" value="{{ old('address') }}" placeholder="name@yourdomain.com" required></div>
<div><label>Display name</label><input name="display_name" value="{{ old('display_name') }}" placeholder="Operations Team"></div><div><label>Status</label><select name="status"><option value="active">Active</option><option value="suspended">Suspended</option></select></div>
<div><label>Mailbox password @if($cpanelConfigured)<span class="required">*</span>@endif</label><input type="password" name="password" autocomplete="new-password" minlength="8" @required($cpanelConfigured)></div>
<div><label>Username</label><input name="username" value="{{ old('username') }}" placeholder="Same as mailbox address"></div>
<div><label>IMAP host</label><input name="imap_host" value="{{ old('imap_host', config('cpanel.mail_host')) }}" placeholder="mail.yourdomain.com"></div><div><label>IMAP port</label><input type="number" name="imap_port" value="{{ old('imap_port',993) }}" min="1" max="65535"></div>
<div><label>SMTP host</label><input name="smtp_host" value="{{ old('smtp_host', config('cpanel.mail_host')) }}" placeholder="mail.yourdomain.com"></div><div><label>SMTP port</label><input type="number" name="smtp_port" value="{{ old('smtp_port',465) }}" min="1" max="65535"></div>
</div><div class="actions"><a href="{{ route('admin.email') }}">Cancel</a><button type="submit">Create mailbox</button></div></form></div>
@endsection
@push('styles')<style>.form-card{max-width:900px;background:rgba(255,255,255,.025);border:1px solid var(--line);border-radius:18px;padding:22px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}label{display:block;font-size:12px;color:#9eb9c4;margin:0 0 7px}input,select{width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid var(--line);background:#071c29;color:#e9f7fb;outline:none}.required{color:#ff9eaa}.errors,.warning,.notice{margin-bottom:16px;padding:12px 14px;border-radius:12px}.errors{background:rgba(210,65,65,.12);color:#ffb0b0}.warning{background:rgba(230,170,55,.1);border:1px solid rgba(230,170,55,.2);color:#f0ce8a}.notice{background:rgba(67,194,137,.1);border:1px solid rgba(67,194,137,.2);color:#a8e5ca}.actions{display:flex;justify-content:flex-end;gap:12px;margin-top:22px;align-items:center}.actions a{color:#8ca9b6;text-decoration:none}.actions button{border:0;border-radius:11px;padding:12px 17px;background:#31afd2;color:#fff;font-weight:700}@media(max-width:650px){.fields{grid-template-columns:1fr}}</style>@endpush
