@extends('layouts.portal')
@section('title','Create Mailbox')
@section('content')
<section class="hero"><div class="eyebrow">MAILBOX MANAGEMENT</div><h1>Create mailbox</h1><p>Create an employee mailbox on the hosting mail server. The mailbox is completely separate from the website and admin authentication.</p></section>
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
@if($cpanelConfigured)<div class="notice">Connected to cPanel. New mailboxes use the hosting account's configured quota (0 means unlimited).</div>@else<div class="warning">cPanel provisioning is not configured yet. Add the cPanel API settings to <code>.env</code> before creating real mailboxes.</div>@endif
<div class="form-card"><form method="POST" action="{{ route('admin.email.store') }}">@csrf
<div class="address-row"><div class="local"><label>Email address</label><input name="local_part" value="{{ old('local_part') }}" placeholder="employee.name" autocomplete="off" required></div><div class="domain">@<strong>{{ $domain }}</strong></div></div>
<div class="fields"><div><label>Display name <small>(optional)</small></label><input name="display_name" value="{{ old('display_name') }}" placeholder="Employee Name"></div><div><label>Password</label><input type="password" name="password" autocomplete="new-password" minlength="10" required></div><div><label>Confirm password</label><input type="password" name="password_confirmation" autocomplete="new-password" minlength="10" required></div></div>
<div class="mail-settings"><i class="fa-solid fa-circle-info"></i><span>Employees will sign in separately at <b>{{ config('cpanel.webmail_url','https://mail.fuelfreepowerplant.com') }}</b>. The main website admin account is not an email mailbox.</span></div>
<div class="actions"><a href="{{ route('admin.email') }}">Cancel</a><button type="submit">Create mailbox</button></div></form></div>
@endsection
@push('styles')<style>.form-card{max-width:850px;background:rgba(255,255,255,.025);border:1px solid var(--line);border-radius:18px;padding:22px}.address-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end;margin-bottom:16px}.local label{display:block}.domain{height:46px;display:flex;align-items:center;padding:0 15px;border:1px solid var(--line);border-radius:11px;background:#071c29;color:#8fb2be;white-space:nowrap}.domain strong{color:#dff7fb;margin-left:4px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:16px}label{display:block;font-size:12px;color:#9eb9c4;margin:0 0 7px}label small{color:#668693}input{width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid var(--line);background:#071c29;color:#e9f7fb;outline:none}.errors,.warning,.notice,.mail-settings{margin-bottom:16px;padding:12px 14px;border-radius:12px}.errors{background:rgba(210,65,65,.12);color:#ffb0b0}.warning{background:rgba(230,170,55,.1);border:1px solid rgba(230,170,55,.2);color:#f0ce8a}.notice{background:rgba(67,194,137,.1);border:1px solid rgba(67,194,137,.2);color:#a8e5ca}.mail-settings{display:flex;gap:10px;align-items:flex-start;background:rgba(69,200,232,.045);border:1px solid rgba(69,200,232,.12);color:#91b3be;font-size:12px;line-height:1.6;margin-top:18px}.mail-settings i{color:#58d4ee;margin-top:2px}.mail-settings b{color:#d8f7fc}.actions{display:flex;justify-content:flex-end;gap:12px;margin-top:22px;align-items:center}.actions a{color:#8ca9b6;text-decoration:none}.actions button{border:0;border-radius:11px;padding:12px 17px;background:#31afd2;color:#fff;font-weight:700}@media(max-width:650px){.fields{grid-template-columns:1fr}.address-row{grid-template-columns:1fr}.domain{height:auto;min-height:44px}}</style>@endpush
