@extends('layouts.portal')
@section('title','Subdomains')
@section('content')
<section class="hero"><div class="eyebrow">INFRASTRUCTURE</div><h1>Subdomains</h1><p>Track managed subdomains, their target and SSL state. DNS/web-server provisioning remains tied to the hosting provider.</p></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="toolbar">@if(auth()->user()->hasPermission('subdomains.manage'))<a class="action" href="{{ route('admin.subdomains.create') }}">＋ Add subdomain</a>@endif</div>
<div class="table-card"><div class="table-wrap"><table><thead><tr><th>Hostname</th><th>Owner</th><th>Target</th><th>Status</th><th>SSL</th><th>Actions</th></tr></thead><tbody>@forelse($subdomains as $item)<tr><td><strong>{{ $item->name }}</strong></td><td>{{ $item->user->name }}</td><td>{{ $item->target ?: '—' }}</td><td>{{ ucfirst($item->status) }}</td><td>{{ $item->ssl_enabled ? 'Enabled' : 'Disabled' }}</td><td>@if(auth()->user()->hasPermission('subdomains.manage'))<form method="POST" action="{{ route('admin.subdomains.destroy',$item) }}" onsubmit="return confirm('Remove this subdomain record?')">@csrf @method('DELETE')<button class="danger">Remove</button></form>@endif</td></tr>@empty<tr><td colspan="6">No subdomains configured.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $subdomains->links() }}</div></div>
@endsection
@push('styles')<style>.toolbar{display:flex;justify-content:flex-end;margin-bottom:14px}.action{padding:11px 15px;border-radius:11px;background:#31afd2;color:#fff;text-decoration:none;font-weight:700;font-size:13px}.notice{padding:12px 14px;border-radius:12px;margin-bottom:14px;background:rgba(67,194,137,.1);border:1px solid rgba(67,194,137,.2);color:#a8e5ca}.table-card{background:rgba(255,255,255,.025);border:1px solid var(--line);border-radius:18px;overflow:hidden}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:820px}th,td{text-align:left;padding:14px 16px;border-bottom:1px solid rgba(255,255,255,.06);font-size:12px}th{color:#74cce9;font-size:10px;text-transform:uppercase;letter-spacing:.08em}td{color:#b5cbd4}.danger{border:0;background:transparent;color:#ff9eaa;cursor:pointer}.pagination{padding:12px}</style>@endpush
