@extends('layouts.portal')
@section('title',$item->exists?'Edit Website Content':'New Website Content')
@section('content')
<section class="hero"><div><span class="eyebrow">PUBLIC WEBSITE CONTROL</span><h1>{{ $item->exists?'Edit':'Create' }} content</h1><p>Publish structured information without editing the public website code.</p></div><a class="back" href="{{ route('admin.site-content.index') }}"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="card"><form method="POST" action="{{ $item->exists ? route('admin.site-content.update',$item) : route('admin.site-content.store') }}">@csrf @if($item->exists) @method('PATCH') @endif
<div class="grid"><div><label>Content type</label><select name="type" required>@foreach($types as $type)<option value="{{ $type }}" @selected(old('type',$item->type)===$type)>{{ ucfirst($type) }}</option>@endforeach</select></div><div><label>Status</label><select name="status" required><option value="draft" @selected(old('status',$item->status)==='draft')>Draft</option><option value="published" @selected(old('status',$item->status)==='published')>Published</option></select></div><div class="full"><label>Title</label><input name="title" value="{{ old('title',$item->title) }}" required maxlength="255"></div><div><label>Slug</label><input name="slug" value="{{ old('slug',$item->slug) }}" maxlength="255" placeholder="Auto-generated if empty"></div><div><label>Sort order</label><input type="number" name="sort_order" value="{{ old('sort_order',$item->sort_order ?? 0) }}" min="0"></div><div class="full"><label>Excerpt</label><textarea name="excerpt" rows="3" maxlength="1000">{{ old('excerpt',$item->excerpt) }}</textarea></div><div class="full"><label>Content</label><textarea name="content" rows="14">{{ old('content',$item->content) }}</textarea></div><div><label>Image path</label><input name="image_path" value="{{ old('image_path',$item->image_path) }}" maxlength="500"></div><div><label>Published at</label><input type="datetime-local" name="published_at" value="{{ old('published_at',$item->published_at?->format('Y-m-d\TH:i')) }}"></div></div><button class="save" type="submit"><i class="fa-solid fa-floppy-disk"></i> {{ $item->exists?'Update':'Create' }} content</button></form></div>
@endsection
@push('styles')<style>.hero{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.hero h1{font-size:clamp(26px,4vw,40px);margin:6px 0}.hero p{color:#7898a5;font-size:11px}.back{padding:10px 13px;border:1px solid var(--line);border-radius:11px;color:#9db9c2;text-decoration:none;font-size:10px}.card{max-width:900px;padding:20px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.02)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.full{grid-column:1/-1}label{display:block;color:#89a7b2;font-size:10px;margin-bottom:7px}input,select,textarea{width:100%;box-sizing:border-box;border:1px solid var(--line);border-radius:10px;background:#061923;color:#e4f3f7;padding:11px;font:inherit;font-size:11px;outline:none}textarea{resize:vertical;line-height:1.6}.save{margin-top:20px;border:0;border-radius:11px;padding:12px 16px;background:#29aaca;color:#fff;font-weight:700}.errors{padding:11px;border-radius:10px;margin-bottom:14px;background:rgba(210,65,65,.12);color:#ffb0b0;font-size:10px}@media(max-width:650px){.hero{align-items:flex-start;gap:12px;flex-direction:column}.grid{grid-template-columns:1fr}.full{grid-column:auto}.save{width:100%}}</style>@endpush
