@extends('layouts.portal')
@section('title','Website Content')
@section('content')
<section class="hero"><div><span class="eyebrow">PUBLIC WEBSITE CONTROL</span><h1>Website Content</h1><p>Manage structured content for the public website.</p></div><a class="primary" href="{{ route('admin.site-content.create') }}"><i class="fa-solid fa-plus"></i> New content</a></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="filters"><a class="{{ !$type?'active':'' }}" href="{{ route('admin.site-content.index') }}">All</a>@foreach($types as $contentType)<a class="{{ $type===$contentType?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>$contentType]) }}">{{ ucfirst($contentType) }}</a>@endforeach</div>
<div class="table-card"><div class="table-head"><span>Content</span><span>Type</span><span>Status</span><span>Actions</span></div>@forelse($items as $item)<div class="row"><div><strong>{{ $item->title }}</strong><small>/{{ $item->slug }}</small></div><span class="type">{{ $item->type }}</span><span class="status {{ $item->status }}">{{ $item->status }}</span><div class="actions"><a href="{{ route('admin.site-content.edit',$item) }}"><i class="fa-solid fa-pen"></i></a><form method="POST" action="{{ route('admin.site-content.destroy',$item) }}" onsubmit="return confirm('Delete this content?')">@csrf @method('DELETE')<button><i class="fa-solid fa-trash"></i></button></form></div></div>@empty<div class="empty"><i class="fa-regular fa-file-lines"></i><strong>No website content yet</strong><span>Create your first structured content item.</span></div>@endforelse</div>{{ $items->links() }}
@endsection
@push('styles')<style>.hero{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.hero h1{margin:6px 0;font-size:clamp(26px,4vw,40px)}.hero p{color:#7898a5;font-size:11px}.primary{padding:11px 15px;border-radius:11px;background:#28aaca;color:white;text-decoration:none;font-size:11px}.filters{display:flex;gap:7px;overflow:auto;scrollbar-width:none;margin-bottom:12px}.filters a{white-space:nowrap;padding:8px 11px;border:1px solid var(--line);border-radius:999px;color:#7898a5;text-decoration:none;font-size:9px}.filters a.active{background:rgba(69,200,232,.12);color:#bcecf5}.table-card{border:1px solid var(--line);border-radius:17px;overflow:hidden;background:rgba(255,255,255,.02)}.table-head,.row{display:grid;grid-template-columns:2fr .8fr .8fr .65fr;gap:12px;align-items:center;padding:13px 15px}.table-head{color:#5f8290;font-size:9px;text-transform:uppercase;border-bottom:1px solid var(--line)}.row{border-bottom:1px solid rgba(255,255,255,.045);font-size:10px}.row:last-child{border:0}.row strong{display:block;color:#d9edf2}.row small{display:block;color:#587784;margin-top:4px}.type{color:#8caab5}.status{font-size:8px;text-transform:uppercase;padding:5px 7px;border-radius:999px;width:max-content}.published{background:rgba(32,212,170,.1);color:#72e5c9}.draft{background:rgba(255,190,70,.08);color:#e6c37c}.actions{display:flex;gap:7px}.actions a,.actions button{width:30px;height:30px;display:grid;place-items:center;border:1px solid var(--line);background:transparent;color:#8bb0bd;border-radius:9px;text-decoration:none}.actions form{margin:0}.notice{padding:11px 13px;margin-bottom:12px;border-radius:11px;background:rgba(67,194,137,.1);color:#a8e5ca;font-size:10px}.empty{min-height:230px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:8px;color:#6f909d}.empty i{font-size:30px}.empty strong{color:#9dbac3}.empty span{font-size:10px}@media(max-width:650px){.hero{align-items:flex-start;flex-direction:column}.table-head{display:none}.row{grid-template-columns:1fr auto}.actions{grid-column:2;grid-row:1/3}.primary{width:100%;text-align:center}}</style>@endpush
