<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::table('site_content_items')->updateOrInsert(
            ['type' => 'company', 'slug' => 'our-technology'],
            [
                'title' => 'Our Technology',
                'excerpt' => 'Fuel-Free Flywheel-Based Clean Energy Technology',
                'content' => <<<'HTML'
<h1>Fuel-Free Flywheel-Based Clean Energy Technology</h1>
<p>FUEL FREE POWER PLANT LIMITED is developing an innovative Flywheel-Based Clean Energy Technology designed to generate reliable electrical power without the continuous consumption of conventional fossil fuels such as diesel, petrol, or natural gas.</p>
<p>Our technology is based on the principle of mechanical energy storage and controlled energy conversion. A high-efficiency electric motor initially brings the flywheel system to its required operating speed. Once the flywheel reaches its designed rotational condition, the stored mechanical energy is managed through an integrated power transmission and generation system to produce electrical energy.</p>

<h2>How Our Technology Works</h2>
<p>The system consists of several interconnected components, including:</p>
<ul>
<li><strong>High-Efficiency Drive Motor</strong> – initiates and maintains the required rotational speed of the flywheel system.</li>
<li><strong>High-Inertia Flywheel</strong> – stores mechanical rotational energy and provides a stable energy source for the generation process.</li>
<li><strong>Mechanical Power Transmission System</strong> – efficiently transfers rotational energy from the flywheel to the generator.</li>
<li><strong>Electrical Generator</strong> – converts mechanical energy into electrical energy.</li>
<li><strong>Control &amp; Synchronization System</strong> – monitors speed, load, voltage, frequency, and other operating parameters to maintain stable power output.</li>
<li><strong>Protection &amp; Safety System</strong> – provides operational protection against abnormal conditions and ensures safe system performance.</li>
</ul>

<h2>Fuel-Free Operation</h2>
<p>The key advantage of our technology is that no continuous fuel input is required during normal power generation. Unlike conventional diesel- or gas-based generators, our proposed system is designed to eliminate the recurring fuel requirement associated with conventional thermal generation.</p>
<p>The technology therefore has the potential to significantly reduce:</p>
<ul>
<li>Fuel consumption and operating costs</li>
<li>Dependence on imported fossil fuels</li>
<li>Carbon emissions and environmental pollution</li>
<li>Electricity generation costs</li>
<li>Long-term energy security risks</li>
</ul>

<h2>Clean, Reliable and Scalable Power</h2>
<p>Our Flywheel-Based Clean Energy Technology is being developed with a focus on reliability, efficiency, scalability, and environmental sustainability.</p>
<p>The technology can potentially be configured for different applications, ranging from backup power and industrial electricity supply to distributed power generation and grid-connected power plants.</p>
<p>We envision a future in which industries, businesses, institutions, and communities can access dependable electricity with substantially lower dependence on conventional fuels.</p>

<h2>Our Vision</h2>
<p>FUEL FREE POWER PLANT LIMITED is committed to advancing innovative energy technologies that can contribute to a cleaner, more sustainable, and economically efficient power sector.</p>
<p>Our goal is to transform the way electricity is generated by developing fuel-free, clean, reliable, and scalable power-generation solutions for the future.</p>
HTML,
                'status' => 'published',
                'published_at' => now(),
                'show_in_navigation' => true,
                'navigation_order' => 3,
                'sort_order' => 3,
                'is_featured' => false,
                'updated_at' => now(),
                'created_at' => now(),
            ]
        );
    }

    public function down(): void
    {
        DB::table('site_content_items')
            ->where('type', 'company')
            ->where('slug', 'our-technology')
            ->delete();
    }
};
