@extends('layouts.public')

@php($siteName = $brand['name'] ?? config('fuelfree.company.name'))

@section('title', 'Gallery — '.$siteName)

@section('content')
<style>:root{--text:#effcff;--muted:#91aeb8;--line:rgba(93,211,238,.16);--cyan:#4fd2ee}*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#020a10,#061721 55%,#020a10);color:var(--text);font-family:Inter,system-ui,sans-serif}a{text-decoration:none;color:inherit}.shell{width:min(1180px,calc(100% - 28px));margin:auto}.hero{padding:55px 0 30px}.eyebrow{font-size:9px;letter-spacing:.2em;color:var(--cyan);text-transform:uppercase}.hero h1{font-size:clamp(38px,6vw,65px);letter-spacing:-.05em;margin:10px 0}.hero p{color:var(--muted);font-size:12px;line-height:1.8}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;padding-bottom:60px}.card{border:1px solid var(--line);border-radius:17px;overflow:hidden;background:rgba(7,30,42,.75);transition:.25s}.card:hover{transform:translateY(-3px);border-color:rgba(93,211,238,.35)}.cover{height:230px;background:#061923}.cover img{width:100%;height:100%;object-fit:cover}.no-cover{height:100%;display:grid;place-items:center;color:#668792}.body{padding:16px}.body h2{font-size:16px;margin:0}.count{display:inline-block;margin-top:11px;padding:5px 8px;border-radius:999px;background:rgba(79,210,238,.08);color:#7fd9e8;font-size:8px}.empty{grid-column:1/-1;text-align:center;padding:60px;border:1px dashed var(--line);border-radius:17px;color:var(--muted)}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr);gap:10px}.cover{height:180px}}@media(max-width:520px){.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cover{height:135px}.body{padding:11px}.body h2{font-size:12px}.hero{padding:43px 0 25px}.hero p{font-size:10px}}</style>
<main class="shell"><section class="hero"><span class="eyebrow">Moments &amp; Media</span><h1>Gallery</h1><p>Explore our events, milestones and selected moments.</p></section><section class="grid">@if($galleries->isEmpty())<div class="empty">No galleries have been published yet.</div>@else @foreach($galleries as $gallery)<a class="card" href="{{ route('gallery.show',['item'=>$gallery->slug]) }}"><div class="cover">@if($gallery->image_path)<img src="{{ asset('storage/'.$gallery->image_path) }}" alt="{{ $gallery->title }}" loading="lazy">@else<div class="no-cover">No cover photo</div>@endif</div><div class="body"><h2>{{ $gallery->title }}</h2><span class="count">{{ $gallery->gallery_media_count }} media</span></div></a>@endforeach @endif</section></main>
@endsection
