@extends('layouts.public')

@php
    $siteName=$brand['name'] ?? config('fuelfree.company.name');
    $media=$item->galleryMedia;
@endphp

@section('title', $item->title.' — '.$siteName)

@section('content')
<style>:root{--text:#effcff;--muted:#91aeb8;--line:rgba(93,211,238,.16);--cyan:#4fd2ee}*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#020a10,#061721,#020a10);color:var(--text);font-family:Inter,system-ui,sans-serif}a{color:inherit;text-decoration:none}.shell{width:min(1180px,calc(100% - 28px));margin:auto}.hero{padding:55px 0 30px}.back{display:inline-block;font-size:10px;padding:9px 12px;border:1px solid var(--line);border-radius:9px;color:#b7d3da;margin-bottom:25px}.eyebrow{font-size:9px;letter-spacing:.2em;color:var(--cyan);text-transform:uppercase}.hero h1{font-size:clamp(35px,6vw,65px);letter-spacing:-.05em;margin:10px 0}.hero p{color:var(--muted);font-size:11px;line-height:1.8;max-width:760px}.viewer{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding-bottom:60px}.media{position:relative;overflow:hidden;border-radius:14px;border:1px solid var(--line);background:#061923;aspect-ratio:1/1}.media img,.media video{width:100%;height:100%;display:block;object-fit:cover}.media img{cursor:zoom-in;transition:.25s}.media:hover img{transform:scale(1.02);filter:brightness(1.08)}.video-mark{position:absolute;left:10px;top:10px;padding:6px 8px;border-radius:8px;background:rgba(0,5,9,.72);font-size:9px;color:#9fe7f4;z-index:2}.empty{grid-column:1/-1;padding:55px;text-align:center;border:1px dashed var(--line);border-radius:18px;color:var(--muted)}.lightbox{display:none;position:fixed;inset:0;z-index:100;background:rgba(0,5,9,.96);align-items:center;justify-content:center;padding:20px}.lightbox.open{display:flex}.lightbox img{max-width:95vw;max-height:90vh;object-fit:contain;border-radius:12px}.close{position:fixed;right:18px;top:18px;width:44px;height:44px;border:1px solid rgba(255,255,255,.18);border-radius:10px;background:rgba(255,255,255,.08);color:#fff;font-size:22px}@media(max-width:900px){.viewer{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.viewer{grid-template-columns:repeat(2,1fr);gap:7px}.hero{padding:43px 0 25px}.media{border-radius:10px}}</style>
<main class="shell"><section class="hero"><a class="back" href="{{ route('site.gallery') }}">← All galleries</a><span class="eyebrow">Photo gallery</span><h1>{{ $item->title }}</h1>@if($item->excerpt)<p>{{ $item->excerpt }}</p>@endif</section><section class="viewer">@if($media->isEmpty())<div class="empty">No photos or videos have been added to this gallery yet.</div>@else @foreach($media as $entry)<div class="media">@if($entry->type==='video')<span class="video-mark">VIDEO</span><video controls preload="metadata" src="{{ asset('storage/'.$entry->path) }}"></video>@else<img src="{{ asset('storage/'.$entry->path) }}" alt="{{ $entry->original_name }}" loading="lazy">@endif</div>@endforeach @endif</section></main><div class="lightbox" id="lightbox"><button class="close" type="button">×</button><img id="lightImg" alt=""></div><script>const box=document.getElementById('lightbox'),li=document.getElementById('lightImg');document.querySelectorAll('.media img').forEach(i=>i.addEventListener('click',()=>{li.src=i.currentSrc||i.src;li.alt=i.alt;box.classList.add('open')}));document.querySelector('.close').onclick=()=>box.classList.remove('open');box.onclick=e=>{if(e.target===box)box.classList.remove('open')};document.onkeydown=e=>{if(e.key==='Escape')box.classList.remove('open')};</script>
@endsection
