@extends('layouts.portal')
@section('title',$popup->exists?'Edit Announcement Banner':'New Announcement Banner')
@section('content')
<section class="hero"><div><span class="eyebrow">HOMEPAGE HIGHLIGHT</span><h1>{{ $popup->exists?'Edit':'Create' }} banner</h1><p>Upload the important notice image your visitors should see when they open the website.</p></div><a class="back" href="{{ route('admin.site-popups.index') }}"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="card"><form method="POST" enctype="multipart/form-data" action="{{ $popup->exists?route('admin.site-popups.update',$popup):route('admin.site-popups.store') }}">@csrf @if($popup->exists) @method('PATCH') @endif
<div class="grid"><div class="full"><label>Banner image {{ $popup->exists?'(leave empty to keep current)':'' }}</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/avif" {{ $popup->exists?'':'required' }}></div><div class="full">@if($popup->image_path)<img class="preview" src="{{ asset('storage/'.$popup->image_path) }}" alt="Current banner">@endif</div><div class="full"><label>Internal title</label><input name="title" value="{{ old('title',$popup->title) }}" maxlength="255" placeholder="e.g. Important notice"></div><div><label>Auto-close after (seconds)</label><input type="number" name="display_seconds" value="{{ old('display_seconds',$popup->display_seconds) }}" min="1" max="3600" placeholder="Leave empty for close button only"></div><div><label>Destination URL (optional)</label><input type="url" name="link_url" value="{{ old('link_url',$popup->link_url) }}" placeholder="https://example.com/notice"></div><div><label>Start time (optional)</label><input type="datetime-local" name="starts_at" value="{{ old('starts_at',$popup->starts_at?->format('Y-m-d\\TH:i')) }}"></div><div><label>End time (optional)</label><input type="datetime-local" name="ends_at" value="{{ old('ends_at',$popup->ends_at?->format('Y-m-d\\TH:i')) }}"></div><div class="full check"><label><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$popup->is_published))> Publish on the public homepage</label></div></div><div class="actions"><a class="back" href="{{ route('admin.site-popups.index') }}">Cancel</a><button class="save" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save banner</button></div></form></div>
@endsection
@push('styles')<style>.card{max-width:1080px;padding:22px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,rgba(8,37,50,.72),rgba(3,19,27,.84));box-shadow:0 14px 38px rgba(0,0,0,.14)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.full{grid-column:1/-1}label{display:block;color:#9ab5be;font-size:10px;font-weight:700;margin-bottom:7px}input{width:100%;box-sizing:border-box;border:1px solid rgba(104,204,235,.14);border-radius:10px;background:#061923;color:#e4f3f7;padding:12px;font:inherit;font-size:11px;min-height:42px;outline:none;transition:border-color .18s,box-shadow .18s}input:focus{border-color:rgba(86,210,238,.5);box-shadow:0 0 0 3px rgba(67,194,229,.07)}.check{padding:12px 14px;border:1px solid rgba(104,204,235,.1);border-radius:11px;background:rgba(67,194,229,.025)}.check label{display:flex;align-items:center;gap:9px;margin:0;color:#b5cbd4}.check input{width:16px;min-height:16px}.preview{width:min(100%,720px);max-height:340px;object-fit:contain;border-radius:14px;border:1px solid var(--line);display:block;background:#061923}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:22px;padding-top:16px;border-top:1px solid rgba(104,204,235,.08)}.back{display:inline-flex;align-items:center;gap:7px;padding:10px 13px;border:1px solid var(--line);border-radius:11px;color:#9db9c2;text-decoration:none;font-size:10px}.save{border:0;border-radius:11px;padding:12px 18px;background:linear-gradient(135deg,#25abc9,#1687a4);color:#fff;font-weight:800;cursor:pointer}@media(max-width:900px){.card{max-width:none}.grid{grid-template-columns:1fr}}@media(max-width:650px){.card{padding:15px;border-radius:15px}.grid{gap:12px}.full{grid-column:auto}.actions{justify-content:stretch;flex-direction:column}.actions>*{width:100%;justify-content:center;text-align:center;box-sizing:border-box}.save{width:100%}.preview{max-height:260px}}</style>@endpush
