@extends('layouts.portal')
@section('title','Announcement Banners')
@section('content')
<section class="hero"><div><span class="eyebrow">PUBLIC WEBSITE CONTROL</span><h1>Announcement banners</h1><p>Publish a homepage image popup for important notices. Set an auto-close timer or leave it empty for visitor-controlled closing.</p></div><a class="action" href="{{ route('admin.site-popups.create') }}"><i class="fa-solid fa-plus"></i> New banner</a></section>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="table-card"><div class="table-wrap"><table><thead><tr><th>Banner</th><th>Status</th><th>Auto close</th><th>Schedule</th><th>Actions</th></tr></thead><tbody>@forelse($popups as $popup)<tr><td><div class="banner-cell"><img src="{{ asset('storage/'.$popup->image_path) }}" alt=""><strong>{{ $popup->title ?: 'Untitled announcement' }}</strong></div></td><td><span class="badge {{ $popup->is_published?'published':'draft' }}">{{ $popup->is_published?'Published':'Draft' }}</span></td><td>{{ $popup->display_seconds ? $popup->display_seconds.' sec' : 'Visitor closes' }}</td><td>{{ $popup->starts_at?->format('d M Y H:i') ?: 'Immediately' }}{{ $popup->ends_at?' → '.$popup->ends_at->format('d M Y H:i'):'' }}</td><td><a class="link" href="{{ route('admin.site-popups.edit',$popup) }}"><i class="fa-solid fa-pen-to-square"></i> Edit</a> <form class="inline" method="POST" action="{{ route('admin.site-popups.destroy',$popup) }}" onsubmit="return confirm('Delete this banner?')">@csrf @method('DELETE')<button><i class="fa-solid fa-trash-can"></i> Delete</button></form></td></tr>@empty<tr><td colspan="5" class="empty">No announcement banners yet.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $popups->links() }}</div></div>
@endsection
@push('styles')<style>.banner-cell{display:flex;align-items:center;gap:12px}.banner-cell img{width:82px;height:46px;object-fit:cover;border-radius:8px;border:1px solid var(--line)}.link{color:#74cce9;text-decoration:none}.inline{display:inline}.inline button{border:0;background:transparent;color:#ff9eaa;cursor:pointer;font:inherit}.badge{display:inline-block;padding:5px 8px;border-radius:99px;font-size:9px}.published{color:#8de8cc;background:rgba(67,194,137,.1)}.draft{color:#ffc77d;background:rgba(255,183,77,.1)}.empty{text-align:center;padding:30px;color:#7895a0}</style>@endpush
@endsection
