@extends('layouts.portal')
@section('title','Homepage Builder')
@section('content')
<section class="hero"><div><span class="eyebrow">WEBSITE / HOMEPAGE</span><h1>Homepage Builder</h1><p>Arrange homepage sections, control visibility, and manage the public composition without touching code.</p></div><a class="back" href="{{ route('admin.site-content.index') }}"><i class="fa-solid fa-arrow-left"></i> Website Content</a></section>
@if(session('status'))<div class="notice">{{session('status')}}</div>@endif @if($errors->any())<div class="errors">{{$errors->first()}}</div>@endif
<form method="POST" action="{{ route('admin.homepage-builder.update') }}" id="home-builder">@csrf
<div class="builder-card">
<div class="builder-head"><div><strong>Homepage Sections</strong><small>Arrange what visitors see. Each section gets its content from its own website module.</small></div><button class="primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Save Layout</button></div>
<div class="helper"><i class="fa-solid fa-circle-info"></i><span><b>Simple rule:</b> turn a section off to hide it; do not delete its content. Edit the actual content from its own module.</span></div>
<div id="section-list">
@php
$icons=['hero'=>'fa-images','welcome'=>'fa-building','statistics'=>'fa-chart-simple','projects'=>'fa-industry','management'=>'fa-users','news'=>'fa-newspaper','gallery'=>'fa-images','cta'=>'fa-paper-plane'];
$countLabels=['hero'=>'sliders','welcome'=>null,'statistics'=>null,'projects'=>'projects','management'=>'management profiles','news'=>'published news & notices','gallery'=>'published galleries','cta'=>null];
@endphp
@foreach($sections as $section)
<div class="section-row" draggable="true" data-key="{{ $section->key }}">
<span class="grip" title="Drag to reorder" aria-label="Drag to reorder"><i class="fa-solid fa-grip-vertical"></i></span>
<div class="section-icon"><i class="fa-solid {{ $icons[$section->key] ?? 'fa-layer-group' }}"></i></div>
<div class="section-copy"><strong>{{ $section->label }}</strong><small>{{ $section->description }} @if(($countLabels[$section->key] ?? null) && isset($counts[$countLabels[$section->key]])) · {{ $counts[$countLabels[$section->key]] }} {{ $countLabels[$section->key] }} @endif</small></div>
<label class="switch" title="{{ $section->is_enabled ? 'Visible on homepage' : 'Hidden from homepage' }}"><input type="checkbox" name="sections[{{ $section->key }}]" value="1" @checked($section->is_enabled) aria-label="Show {{ $section->label }} on homepage"><span></span></label>
</div>
@endforeach
</div>
<div id="order-fields"></div>
</div>
</form>
@endsection
@push('styles')<style>
.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:22px}.eyebrow{font-size:9px;letter-spacing:.18em;color:#54cde8}.hero h1{margin:6px 0;font-size:clamp(28px,3.2vw,44px)}.hero p{margin:0;color:#7898a5;font-size:12px;line-height:1.65;max-width:720px}.back{font-size:10px;color:#9bc0ca;text-decoration:none;white-space:nowrap}.builder-card{border:1px solid var(--line);border-radius:17px;background:linear-gradient(145deg,rgba(8,38,52,.84),rgba(3,21,30,.82));overflow:hidden}.builder-head{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:16px;border-bottom:1px solid var(--line)}.builder-head strong{display:block;color:#e7f8fb;font-size:13px}.builder-head small{display:block;color:#6f8e98;font-size:9px;margin-top:4px}.primary{display:inline-flex;align-items:center;gap:8px;border:0;border-radius:11px;padding:10px 14px;background:linear-gradient(135deg,#25abc9,#1687a4);color:#fff;font-size:10px;font-weight:800;cursor:pointer}.helper{display:flex;gap:9px;align-items:flex-start;padding:12px 16px;color:#7696a1;font-size:9px;line-height:1.55;border-bottom:1px solid rgba(104,204,235,.08);background:rgba(67,194,229,.025)}.helper i{color:#5bd5ed;margin-top:1px}.helper b{color:#a9d7df}.section-row{display:grid;grid-template-columns:26px 40px minmax(0,1fr) 48px;gap:11px;align-items:center;margin:10px;padding:12px;border:1px solid rgba(104,204,235,.12);border-radius:12px;background:rgba(2,15,23,.65);transition:.2s}.section-row.dragging{opacity:.4}.section-row.drop-target{outline:1px dashed #56d2ee}.grip{color:#598592;cursor:grab}.section-icon{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;color:#62d9ee;background:rgba(67,194,229,.08)}.section-copy{min-width:0}.section-copy strong{display:block;font-size:11px;color:#dff4f7}.section-copy small{display:block;font-size:8px;color:#6d8c97;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.switch{position:relative;width:40px;height:22px;display:block}.switch input{opacity:0;width:0;height:0}.switch span{position:absolute;inset:0;border-radius:99px;background:#18303a;border:1px solid #31505a;cursor:pointer}.switch span:before{content:'';position:absolute;width:16px;height:16px;left:2px;top:2px;border-radius:50%;background:#78939c;transition:.2s}.switch input:checked+span{background:rgba(42,183,213,.22);border-color:rgba(86,210,238,.55)}.switch input:checked+span:before{transform:translateX(18px);background:#69e0f3}@media(max-width:600px){.hero{display:block}.back{display:inline-block;margin-top:12px}.builder-head{align-items:flex-start;flex-direction:column}.section-row{grid-template-columns:22px 36px minmax(0,1fr) 40px;padding:10px}.section-icon{width:36px;height:36px}.section-copy small{white-space:normal;line-height:1.35}}
</style>@endpush
@push('scripts')<script>
(()=>{const list=document.getElementById('section-list'),fields=document.getElementById('order-fields');if(!list||!fields)return;let drag=null;const sync=()=>{fields.innerHTML=[...list.querySelectorAll('.section-row')].map(x=>'<input type="hidden" name="section_order[]" value="'+x.dataset.key+'">').join('')};
const clearTargets=()=>list.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'));
const save=()=>{sync();document.getElementById('home-builder').requestSubmit();};list.querySelectorAll('.section-row').forEach(row=>{row.addEventListener('dragstart',()=>{drag=row;row.classList.add('dragging')});row.addEventListener('dragover',e=>{e.preventDefault();row.classList.add('drop-target')});row.addEventListener('dragleave',()=>row.classList.remove('drop-target'));row.addEventListener('drop',e=>{e.preventDefault();row.classList.remove('drop-target');if(!drag||drag===row)return;const rect=row.getBoundingClientRect();if(e.clientY<rect.top+rect.height/2)list.insertBefore(drag,row);else list.insertBefore(drag,row.nextSibling);sync()});row.addEventListener('dragend',()=>{row.classList.remove('dragging');drag=null;clearTargets();sync()});row.addEventListener('touchcancel',()=>{drag=null;clearTargets()})});sync();document.getElementById('home-builder').addEventListener('submit',sync)})();
</script>@endpush