<!doctype html>
@php
$brand=\App\Models\SystemSetting::query()->whereIn('key',['company.name','company.logo_path'])->pluck('value','key');
$dashboardName=$brand->get('company.name')?:config('fuelfree.company.name');$dashboardLogo=$brand->get('company.logo_path');
$websiteOpen=request()->routeIs('admin.site-content*','admin.site-popups*','admin.settings*','admin.plants*');
@endphp
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Dashboard') — {{ $dashboardName }}</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color-scheme:dark;--bg:#031019;--line:rgba(104,204,235,.13);--text:#eaf8fb;--muted:#86a5b4}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:radial-gradient(circle at 75% 0,rgba(25,147,181,.14),transparent 28%),var(--bg);color:var(--text);overflow-x:hidden}a,button{font:inherit}.app{min-height:100vh;display:grid;grid-template-columns:250px 1fr}.sidebar{position:sticky;top:0;height:100vh;padding:18px 14px;border-right:1px solid var(--line);background:rgba(3,16,25,.86);backdrop-filter:blur(18px);overflow-y:auto}.brand{display:flex;align-items:center;gap:10px;padding:8px 9px 22px}.brand-logo,.topbar-brand img{object-fit:contain;border-radius:10px}.brand-logo{width:38px;height:38px}.brand-mark{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:rgba(67,194,229,.08);color:#61d8f1;border:1px solid var(--line)}.brand-text{min-width:0}.brand-text small{display:block;letter-spacing:.16em;color:#61c9e8;font-size:8px;text-transform:uppercase}.brand-text strong{display:block;margin-top:4px;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nav{display:grid;gap:5px}.nav>a,.nav-summary{display:flex;align-items:center;gap:10px;padding:11px;border-radius:11px;color:var(--muted);text-decoration:none;font-size:12px;cursor:pointer}.nav>a:hover,.nav>a.active,.nav details[open]>.nav-summary,.nav-summary:hover{background:rgba(67,194,229,.09);color:var(--text)}.nav-icon{width:20px;height:20px;display:grid;place-items:center;flex:0 0 20px}.nav-summary{list-style:none}.nav-summary::-webkit-details-marker{display:none}.chevron{margin-left:auto;font-size:9px;transition:.2s}.nav details[open] .chevron{transform:rotate(180deg)}.subnav{display:grid;gap:3px;margin:2px 0 4px 30px;padding-left:10px;border-left:1px solid rgba(104,204,235,.12)}.subnav a{display:flex;align-items:center;gap:8px;padding:8px 9px;border-radius:9px;color:#7697a4;text-decoration:none;font-size:10px}.subnav a:hover,.subnav a.active{color:#d9f3f7;background:rgba(67,194,229,.07)}.subnav i{width:14px;text-align:center;color:#5fcfe9;font-size:9px}.main{min-width:0}.topbar{height:70px;display:flex;align-items:center;justify-content:space-between;padding:0 clamp(16px,4vw,42px);border-bottom:1px solid var(--line);background:rgba(3,16,25,.62);backdrop-filter:blur(16px);position:sticky;top:0;z-index:40}.topbar-brand{display:flex;align-items:center;gap:9px;min-width:0;color:inherit;text-decoration:none}.topbar-brand img{width:30px;height:30px}.topbar-title{font-size:13px;color:#c6e1e8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.profile-trigger{width:40px;height:40px;border:1px solid rgba(104,204,235,.18);border-radius:13px;background:rgba(67,194,229,.08);color:#9fd8e8;display:grid;place-items:center;text-decoration:none}.content{padding:clamp(18px,4vw,40px);max-width:1500px}.mobile-nav,.mobile-drawer,.drawer-backdrop{display:none}
@media(max-width:1050px){.app{grid-template-columns:220px 1fr}}@media(max-width:700px){.app{display:block}.sidebar{display:none}.main{padding-bottom:84px}.topbar{height:62px;padding:0 14px}.content{padding:20px 14px}.mobile-nav{position:fixed;display:flex;gap:5px;left:8px;right:8px;bottom:calc(7px + env(safe-area-inset-bottom));height:68px;padding:6px;z-index:80;border:1px solid rgba(104,204,235,.18);border-radius:20px;background:rgba(4,22,32,.95);box-shadow:0 18px 55px rgba(0,0,0,.42);backdrop-filter:blur(22px);overflow-x:auto;overflow-y:hidden;scrollbar-width:thin;scrollbar-color:rgba(104,204,235,.35) transparent;-webkit-overflow-scrolling:touch}.mobile-nav::-webkit-scrollbar{height:3px}.mobile-nav::-webkit-scrollbar-thumb{background:rgba(104,204,235,.35);border-radius:99px}.mobile-nav a,.mobile-more{min-width:68px;flex:0 0 68px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;border-radius:14px;color:#7896a3;text-decoration:none;font-size:8px;white-space:nowrap}.mobile-nav a.active,.mobile-more.active{color:#eaf8fb;background:rgba(67,194,229,.1)}.mobile-nav i,.mobile-more i{font-size:17px}.mobile-more{border:0;background:transparent}.mobile-drawer{position:fixed;display:none;z-index:90;left:10px;right:10px;bottom:82px;max-height:min(70vh,520px);overflow-y:auto;padding:12px;border:1px solid rgba(104,204,235,.18);border-radius:18px;background:rgba(4,22,32,.98);box-shadow:0 22px 70px rgba(0,0,0,.5);backdrop-filter:blur(22px)}.mobile-drawer.open{display:block}.mobile-drawer-title{display:flex;justify-content:space-between;padding:3px 5px 10px;color:#dff7fb;font-size:11px;font-weight:800}.mobile-drawer a{display:flex;align-items:center;gap:9px;padding:11px;border-radius:12px;color:#9db8c2;text-decoration:none;background:rgba(255,255,255,.025);font-size:10px;margin-bottom:5px}.mobile-drawer a:hover,.mobile-drawer a.active{background:rgba(67,194,229,.08);color:#eaf8fb}.mobile-drawer i{width:20px;text-align:center;color:#61d8f1}.drawer-backdrop{display:none;position:fixed;inset:0;z-index:85;background:rgba(0,0,0,.35)}.drawer-backdrop.open{display:block}}
</style>@stack('head') @stack('styles')</head><body><div class="app"><aside class="sidebar"><div class="brand">@if($dashboardLogo)<img class="brand-logo" src="{{ asset('storage/'.$dashboardLogo) }}" alt="{{ $dashboardName }}">@else<span class="brand-mark"><i class="fa-solid fa-bolt"></i></span>@endif<div class="brand-text"><small>Administration</small><strong>{{ $dashboardName }}</strong></div></div><nav class="nav">
@if(auth()->user()->hasRole(['super-admin','administrator','project-manager']))<a class="{{ request()->routeIs('admin.dashboard')?'active':'' }}" href="{{ route('admin.dashboard') }}"><span class="nav-icon"><i class="fa-solid fa-house"></i></span>Overview</a>@endif
@if(auth()->user()->hasPermission('website.view'))<details {{ $websiteOpen?'open':'' }}><summary class="nav-summary"><span class="nav-icon"><i class="fa-solid fa-globe"></i></span>Website Sections<i class="fa-solid fa-chevron-down chevron"></i></summary><div class="subnav">
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='company'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'company']) }}"><i class="fa-solid fa-building"></i>Company &amp; About</a>
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='management'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'management']) }}"><i class="fa-solid fa-people-group"></i>Management</a>
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='news'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'news']) }}"><i class="fa-solid fa-newspaper"></i>News &amp; Notices</a>
<a class="{{ request()->routeIs('admin.site-popups*')?'active':'' }}" href="{{ route('admin.site-popups.index') }}"><i class="fa-solid fa-bullhorn"></i>Homepage Highlights</a>
<a class="{{ request()->routeIs('admin.plants*')?'active':'' }}" href="{{ route('admin.plants.index') }}"><i class="fa-solid fa-bolt"></i>Power Plants &amp; Projects</a>
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='resource'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'resource']) }}"><i class="fa-solid fa-folder-open"></i>Resources &amp; Downloads</a>
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='gallery'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'gallery']) }}"><i class="fa-solid fa-images"></i>Gallery &amp; Media</a>
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='sustainability'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'sustainability']) }}"><i class="fa-solid fa-leaf"></i>Sustainability</a>
<a class="{{ request()->routeIs('admin.settings*')?'active':'' }}" href="{{ route('admin.settings') }}"><i class="fa-solid fa-sliders"></i>Website Settings</a>
</div></details>@endif
@if(auth()->user()->hasPermission('email.view'))<a class="{{ request()->routeIs('admin.email*')?'active':'' }}" href="{{ route('admin.email') }}"><span class="nav-icon"><i class="fa-solid fa-envelope"></i></span>Email</a>@endif
@if(auth()->user()->hasPermission('documents.view'))<a class="{{ request()->routeIs('admin.documents*')?'active':'' }}" href="{{ route('admin.documents') }}"><span class="nav-icon"><i class="fa-solid fa-folder-open"></i></span>Documents</a>@endif
@if(auth()->user()->hasPermission('users.view'))<a class="{{ request()->routeIs('admin.users*')?'active':'' }}" href="{{ route('admin.users.index') }}"><span class="nav-icon"><i class="fa-solid fa-users"></i></span>Users</a>@endif
@if(auth()->user()->hasPermission('settings.manage'))<a class="{{ request()->routeIs('admin.settings*')?'active':'' }}" href="{{ route('admin.settings') }}"><span class="nav-icon"><i class="fa-solid fa-gear"></i></span>Settings</a>@endif
</nav></aside><main class="main"><header class="topbar"><a class="topbar-brand" href="{{ route('admin.dashboard') }}">@if($dashboardLogo)<img src="{{ asset('storage/'.$dashboardLogo) }}" alt="{{ $dashboardName }}">@else<span class="brand-mark"><i class="fa-solid fa-bolt"></i></span>@endif<span class="topbar-title">{{ $dashboardName }}</span></a><a class="profile-trigger" href="{{ route('profile') }}" aria-label="My profile"><i class="fa-solid fa-user"></i></a></header><div class="content">@yield('content')</div></main></div>
<div class="drawer-backdrop" id="drawer-backdrop"></div><nav class="mobile-nav">
@if(auth()->user()->hasRole(['super-admin','administrator','project-manager']))<a class="{{ request()->routeIs('admin.dashboard')?'active':'' }}" href="{{ route('admin.dashboard') }}"><i class="fa-solid fa-house"></i><span>Overview</span></a>@endif
@if(auth()->user()->hasPermission('website.view'))<button class="mobile-more {{ $websiteOpen?'active':'' }}" id="website-menu" type="button"><i class="fa-solid fa-globe"></i><span>Website</span></button>@endif
@if(auth()->user()->hasPermission('email.view'))<a class="{{ request()->routeIs('admin.email*')?'active':'' }}" href="{{ route('admin.email') }}"><i class="fa-solid fa-envelope"></i><span>Email</span></a>@endif
@if(auth()->user()->hasPermission('documents.view'))<a class="{{ request()->routeIs('admin.documents*')?'active':'' }}" href="{{ route('admin.documents') }}"><i class="fa-solid fa-folder-open"></i><span>Files</span></a>@endif
@if(auth()->user()->hasPermission('users.view'))<a class="{{ request()->routeIs('admin.users*')?'active':'' }}" href="{{ route('admin.users.index') }}"><i class="fa-solid fa-users"></i><span>Users</span></a>@endif
@if(auth()->user()->hasPermission('settings.manage'))<a class="{{ request()->routeIs('admin.settings*')?'active':'' }}" href="{{ route('admin.settings') }}"><i class="fa-solid fa-gear"></i><span>Settings</span></a>@endif
</nav>
@if(auth()->user()->hasPermission('website.view'))<div class="mobile-drawer" id="website-drawer"><div class="mobile-drawer-title"><span><i class="fa-solid fa-globe"></i> Website Sections</span><span>Menu</span></div>
<a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='company'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'company']) }}"><i class="fa-solid fa-building"></i>Company &amp; About</a><a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='management'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'management']) }}"><i class="fa-solid fa-people-group"></i>Management</a><a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='news'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'news']) }}"><i class="fa-solid fa-newspaper"></i>News &amp; Notices</a><a class="{{ request()->routeIs('admin.site-popups*')?'active':'' }}" href="{{ route('admin.site-popups.index') }}"><i class="fa-solid fa-bullhorn"></i>Homepage Highlights</a><a class="{{ request()->routeIs('admin.plants*')?'active':'' }}" href="{{ route('admin.plants.index') }}"><i class="fa-solid fa-bolt"></i>Power Plants &amp; Projects</a><a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='resource'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'resource']) }}"><i class="fa-solid fa-folder-open"></i>Resources &amp; Downloads</a><a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='gallery'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'gallery']) }}"><i class="fa-solid fa-images"></i>Gallery &amp; Media</a><a class="{{ request()->routeIs('admin.site-content*')&&request('type')==='sustainability'?'active':'' }}" href="{{ route('admin.site-content.index',['type'=>'sustainability']) }}"><i class="fa-solid fa-leaf"></i>Sustainability</a><a class="{{ request()->routeIs('admin.settings*')?'active':'' }}" href="{{ route('admin.settings') }}"><i class="fa-solid fa-sliders"></i>Website Settings</a></div>@endif
<script>(()=>{const b=document.getElementById('website-menu'),d=document.getElementById('website-drawer'),o=document.getElementById('drawer-backdrop');const close=()=>{d?.classList.remove('open');o?.classList.remove('open');b?.classList.remove('active')};b?.addEventListener('click',()=>{const open=!d.classList.contains('open');d.classList.toggle('open',open);o.classList.toggle('open',open);b.classList.toggle('active',open)});o?.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})})();</script>@stack('scripts')</body></html>
