@extends('layouts.portal')
@section('title',$folder->exists?'Edit Profile Folder':'New Profile Folder')
@section('content')
<section class="hero"><div><span class="eyebrow">GLOBAL · PROFILE BUILDER</span><h1>{{ $folder->exists?'Edit folder':'Create folder' }}</h1><p>The folder name becomes the public leadership section title and its URL slug.</p></div><a class="back" href="{{ route('admin.profile-builder.index') }}"><i class="fa-solid fa-arrow-left"></i> Back to Profile Builder</a></section>
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="card form"><form method="POST" action="{{ $folder->exists?route('admin.profile-builder.folders.update',$folder):route('admin.profile-builder.folders.store') }}">@csrf @if($folder->exists)@method('PATCH')@endif
<label>Folder name</label><input name="name" required maxlength="120" value="{{ old('name',$folder->name) }}" placeholder="Board of Directors"><div class="help">Example: <strong>Board of Directors</strong> → <strong>/board-of-directors</strong></div>
<label>Status</label><select name="status"><option value="published" @selected(old('status',$folder->status)==='published')>Published</option><option value="draft" @selected(old('status',$folder->status)==='draft')>Draft</option></select>
<div class="actions"><a class="back" href="{{ route('admin.profile-builder.index') }}">Cancel</a><button class="save" type="submit"><i class="fa-solid fa-floppy-disk"></i> {{ $folder->exists?'Save folder':'Create folder' }}</button></div></form></div>
@endsection
@push('styles')<style>.hero{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:20px}.eyebrow{font-size:9px;letter-spacing:.16em;color:#54cde8}.hero h1{margin:6px 0;font-size:clamp(27px,4vw,42px)}.hero p{margin:0;color:#7898a5;font-size:11px;max-width:720px;line-height:1.6}.back{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:10px 13px;border:1px solid var(--line);border-radius:11px;color:#9db9c2;text-decoration:none;font-size:10px}.card.form{max-width:720px;padding:20px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.02)}label{display:block;color:#8aa7b1;font-size:9px;margin:0 0 6px}input,select{width:100%;border:1px solid var(--line);border-radius:10px;background:#061923;color:#e4f3f7;padding:11px;font:inherit;font-size:11px;outline:none;margin-bottom:8px}.help{color:#718f99;font-size:9px;line-height:1.6;margin:0 0 14px}.help strong{color:#9eddec}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.save{border:0;border-radius:11px;padding:12px 16px;background:linear-gradient(135deg,#25abc9,#1687a4);color:#fff;font-weight:800;font-size:10px}.errors{padding:11px;border-radius:10px;margin-bottom:14px;background:rgba(210,65,65,.12);color:#ffb0b0;font-size:10px}@media(max-width:650px){.hero{align-items:flex-start;flex-direction:column}.card.form{padding:14px}.actions>*{flex:1;text-align:center}}
</style>@endpush
