@extends('layouts.portal')
@section('title',$member->exists?'Edit Management Profile':'Add Management Member')
@section('content')
<section class="hero"><div><span class="eyebrow">MANAGEMENT</span><h1>{{ $member->exists?'Edit profile':'Add management member' }}</h1></div><a class="back" href="{{ route('admin.management.index') }}"><i class="fa-solid fa-arrow-left"></i> Back</a></section>
@if($errors->any())<div class="errors">{{ $errors->first() }}</div>@endif
<div class="card form"><form method="POST" enctype="multipart/form-data" action="{{ $member->exists?route('admin.management.update',$member):route('admin.management.store') }}">@csrf @if($member->exists)@method('PATCH')@endif
<div class="grid"><div class="full"><label>Full name</label><input name="title" required maxlength="255" value="{{ old('title',$member->title) }}"></div><div><label>Designation</label><input name="designation" required maxlength="255" value="{{ old('designation',$member->designation ?: $member->excerpt) }}"></div><div><label>Phone / mobile</label><input name="phone" required maxlength="50" value="{{ old('phone',$member->phone) }}"></div><div><label>Official email</label><input type="email" name="email" maxlength="255" value="{{ old('email',$member->email) }}"></div><div><label>Status</label><select name="status"><option value="published" @selected(old('status',$member->status)==='published')>Published</option><option value="draft" @selected(old('status',$member->status)==='draft')>Draft</option></select></div><div><label>Publish date/time</label><input type="datetime-local" name="published_at" value="{{ old('published_at',$member->published_at?->format('Y-m-d\TH:i')) }}"></div></div>
<div class="section-title"><i class="fa-solid fa-arrows-up-down"></i><strong>Public order</strong><span>Use Drag & Drop from the Management Team list to change the order.</span></div>
<div class="section-title"><i class="fa-solid fa-image"></i><strong>Profile photo</strong></div><div class="media-row"><label class="upload"><input type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp"><i class="fa-solid fa-cloud-arrow-up"></i><b>Choose photo</b></label>@if($member->image_path)<div class="media-preview"><img src="{{ asset('storage/'.$member->image_path) }}" alt=""><button type="submit" name="remove_profile_photo" value="1" class="remove" onclick="return confirm('Remove profile photo?')"><i class="fa-solid fa-trash"></i> Remove photo</button></div>@endif</div>
<div class="section-title"><i class="fa-regular fa-address-card"></i><strong>Visiting card</strong></div><div class="media-row"><label class="upload"><input type="file" name="visiting_card" accept="image/jpeg,image/png,image/webp,application/pdf"><i class="fa-solid fa-address-card"></i><b>Choose visiting card</b></label>@if($member->visiting_card_path)<div class="card-file"><a href="{{ asset('storage/'.$member->visiting_card_path) }}" target="_blank" rel="noopener"><i class="fa-regular fa-eye"></i> View current card</a><button type="submit" name="remove_visiting_card" value="1" class="remove" onclick="return confirm('Remove visiting card?')"><i class="fa-solid fa-trash"></i> Remove card</button></div>@endif</div>
<div class="section-title"><i class="fa-solid fa-align-left"></i><strong>Professional profile</strong></div><textarea name="content" rows="8">{{ old('content',$member->content) }}</textarea>
<div class="actions"><a class="back" href="{{ route('admin.management.index') }}">Cancel</a><button class="save" type="submit"><i class="fa-solid fa-floppy-disk"></i> {{ $member->exists?'Save changes':'Create profile' }}</button></div></form></div>
@endsection
@push('styles')<style>.hero{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:20px}.eyebrow{font-size:9px;letter-spacing:.16em;color:#54cde8}.hero h1{margin:6px 0;font-size:clamp(27px,4vw,42px)}.back{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:10px 13px;border:1px solid var(--line);border-radius:11px;color:#9db9c2;text-decoration:none;font-size:10px}.card.form{max-width:1100px;padding:20px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.02)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:13px;padding-bottom:8px}.full{grid-column:1/-1}label{display:block;color:#8aa7b1;font-size:9px;margin-bottom:6px}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:10px;background:#061923;color:#e4f3f7;padding:11px;font:inherit;font-size:11px;outline:none}textarea{resize:vertical;line-height:1.7}.section-title{display:flex;align-items:center;gap:10px;padding:15px 0 9px;border-bottom:1px solid rgba(104,204,235,.08);color:#dceff3;font-size:11px}.section-title i{color:#62d6ef}.section-title span{margin-left:auto;color:#678692;font-size:9px;font-weight:400}.media-row{display:flex;gap:10px;padding:14px 0}.upload{flex:1;min-height:100px;border:1px dashed rgba(104,204,235,.2);border-radius:13px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;color:#d9f1f5;cursor:pointer;font-size:10px}.upload input{display:none}.upload i{font-size:23px;color:#5bd2eb}.media-preview,.card-file{width:180px;border:1px solid var(--line);border-radius:13px;overflow:hidden;background:#061923;display:flex;flex-direction:column}.media-preview img{width:100%;height:135px;object-fit:contain;background:#fff}.remove{border:0;padding:9px;background:rgba(220,65,65,.08);color:#ff9d9d;font-size:9px;cursor:pointer}.card-file{padding:10px;justify-content:center;gap:9px}.card-file a{color:#8fd5e4;text-decoration:none;font-size:9px;padding:8px}.actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.save{border:0;border-radius:11px;padding:12px 16px;background:linear-gradient(135deg,#25abc9,#1687a4);color:#fff;font-weight:800;font-size:10px}.errors{padding:11px;border-radius:10px;margin-bottom:14px;background:rgba(210,65,65,.12);color:#ffb0b0;font-size:10px}@media(max-width:650px){.hero{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}.full{grid-column:auto}.section-title span{margin-left:0;display:block;width:100%;line-height:1.5}.media-row{flex-direction:column}.media-preview,.card-file{width:100%}.media-preview img{height:220px}.actions>*{flex:1;text-align:center}}
</style>@endpush
