@extends('layouts.portal')
@section('title',ucfirst($area).' Builder')
@section('content')
<section class="hero"><div><span class="eyebrow">DESIGN &amp; LAYOUT</span><h1>{{ucfirst($area)}} Builder</h1><p>Control the {{ $area }} composition from one place. Changes are stored as global layout settings.</p></div><div class="tabs"><a class="{{$area==='header'?'active':''}}" href="{{route('admin.design.index',['area'=>'header'])}}">Header</a><a class="{{$area==='footer'?'active':''}}" href="{{route('admin.design.index',['area'=>'footer'])}}">Footer</a></div></section>
@if(session('status'))<div class="notice">{{session('status')}}</div>@endif
<form method="POST" action="{{route('admin.design.update')}}">@csrf<input type="hidden" name="area" value="{{$area}}">
<div class="card"><div class="card-head"><div><strong>{{ucfirst($area)}} Components</strong><small>Enable or disable components while preserving their underlying content.</small></div><button class="primary">Save Layout</button></div>
@php($labels=['logo'=>'Logo','navigation'=>'Navigation','social'=>'Social Links','mobile'=>'Mobile Header','portal'=>'Portal / Login State','columns'=>'Footer Columns','links'=>'Footer Links','contact'=>'Contact Information','copyright'=>'Copyright'])
@foreach($settings as $key=>$enabled)<label class="setting"><span><b>{{$labels[$key]??ucwords(str_replace('_',' ',$key))}}</b><small>Global {{str_replace('_',' ',$key)}} visibility</small></span><span class="switch"><input type="checkbox" name="settings[{{$key}}]" value="1" @checked($enabled)><i></i></span></label>@endforeach
</div></form>
@endsection
@push('styles')<style>
.hero{display:flex;justify-content:space-between;align-items:flex-end;gap:24px;margin-bottom:22px}.eyebrow{font-size:9px;letter-spacing:.18em;color:#54cde8}.hero h1{margin:6px 0;font-size:clamp(28px,3.2vw,44px)}.hero p{margin:0;color:#7898a5;font-size:12px;line-height:1.65;max-width:700px}.tabs{display:flex;gap:6px}.tabs a{padding:9px 13px;border:1px solid var(--line);border-radius:9px;color:#7f9da7;text-decoration:none;font-size:10px}.tabs a.active{color:#eaf8fb;background:rgba(67,194,229,.1);border-color:rgba(104,204,235,.25)}.card{border:1px solid var(--line);border-radius:17px;background:linear-gradient(145deg,rgba(8,38,52,.84),rgba(3,21,30,.82));overflow:hidden}.card-head{display:flex;justify-content:space-between;align-items:center;padding:16px;border-bottom:1px solid var(--line)}.card-head strong{display:block;font-size:13px}.card-head small{display:block;color:#6f8e98;font-size:9px;margin-top:4px}.primary{border:0;border-radius:10px;padding:10px 14px;background:#1687a4;color:#fff;font-size:10px;font-weight:800;cursor:pointer}.setting{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:15px 17px;border-bottom:1px solid rgba(104,204,235,.07)}.setting:last-child{border-bottom:0}.setting b{display:block;font-size:11px;color:#dff4f7}.setting small{display:block;color:#6c8994;font-size:8px;margin-top:4px}.switch{width:40px;height:22px;position:relative;flex:0 0 auto}.switch input{opacity:0;width:0;height:0}.switch i{position:absolute;inset:0;border-radius:99px;background:#18303a;border:1px solid #31505a}.switch i:before{content:'';position:absolute;width:16px;height:16px;left:2px;top:2px;border-radius:50%;background:#78939c;transition:.2s}.switch input:checked+i{background:rgba(42,183,213,.22);border-color:rgba(86,210,238,.55)}.switch input:checked+i:before{transform:translateX(18px);background:#69e0f3}@media(max-width:650px){.hero{display:block}.tabs{margin-top:14px}.card-head{align-items:flex-start;gap:12px}.card-head small{max-width:220px}}
</style>@endpush