@extends('layouts.portal')
@section('title', $mode === 'create' ? 'Create News & Event' : 'Edit News & Event')
@section('content')
<div style="max-width:1500px;margin:auto;color:#eaf8fb">
<header style="display:flex;justify-content:space-between;align-items:flex-end;gap:20px;padding:6px 0 20px"><div><div style="font-size:9px;font-weight:900;letter-spacing:.15em;color:#55d8ef">CANONICAL EDITOR · NEWS & EVENT</div><h1 style="font-size:clamp(26px,3vw,38px);margin:5px 0">{{ $mode === 'create' ? 'Create News / Event' : 'Edit News / Event' }}</h1><p style="margin:0;color:#7897a3;font-size:11px">The same Canonical Editor contract is used here and across the CMS.</p></div><div style="display:flex;gap:7px"><a href="{{ route('admin.news_and_event.index') }}" style="display:inline-flex;align-items:center;padding:0 13px;min-height:40px;border-radius:10px;border:1px solid rgba(103,208,234,.14);color:#a7c1c9;text-decoration:none;font-size:10px">Back</a><button type="submit" form="news-event-form" style="border:0;padding:0 14px;border-radius:10px;background:linear-gradient(135deg,#28b6d6,#168da8);color:#fff;font-weight:800">Save</button></div></header>
@if($errors->any())<div style="padding:10px 12px;border-radius:10px;background:rgba(255,87,108,.08);border:1px solid rgba(255,87,108,.18);color:#ffacb8;font-size:10px;margin-bottom:12px">{{ $errors->first() }}</div>@endif
<form id="news-event-form" method="POST" action="{{ $mode === 'create' ? route('admin.news_and_event.store') : route('admin.news_and_event.update',$item) }}">@csrf @if($mode === 'edit')@method('PATCH')@endif
<div style="display:grid;grid-template-columns:285px minmax(0,1fr);gap:14px;align-items:start"><aside style="display:grid;gap:10px"><section class="ne-card"><h2>Identity</h2><label>Title<input name="title" required maxlength="180" value="{{ old('title',$item->title) }}"></label><label>Slug<input name="slug" maxlength="180" value="{{ old('slug',$item->slug) }}"><small>Leave blank to generate automatically.</small></label><label>Type<select name="type"><option value="news" @selected(old('type',$item->type)==='news')>News</option><option value="announcement" @selected(old('type',$item->type)==='announcement')>Announcement / Event</option></select></label><label>Introduction<textarea name="excerpt" maxlength="1000" rows="5">{{ old('excerpt',$item->excerpt) }}</textarea></label></section><section class="ne-card"><h2>Publishing</h2><label class="check"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$item->is_featured))><span>Featured item</span></label><label>Status<select name="status"><option value="draft" @selected(old('status',$item->status)==='draft')>Draft</option><option value="published" @selected(old('status',$item->status)==='published')>Published</option></select></label></section><section class="ne-card"><h2>SEO</h2><label>Meta title<input name="meta_title" maxlength="255" value="{{ old('meta_title',$item->meta_title ?? '') }}"></label><label>Meta description<textarea name="meta_description" maxlength="1000" rows="5">{{ old('meta_description',$item->meta_description ?? '') }}</textarea></label></section></aside><main><section class="ne-card" style="overflow:visible"><div style="padding:15px;border-bottom:1px solid rgba(103,208,234,.1)"><span style="font-size:8px;letter-spacing:.14em;font-weight:900;color:#58d8ed">CANONICAL EDITOR</span><h2 style="margin:4px 0;font-size:14px">Global CMS Editor</h2><p style="margin:0;color:#668590;font-size:9px">Rich text, media, embeds, tables, CTA buttons, columns, HTML source and preview.</p></div><div style="padding:12px"><textarea id="global-cms-content" name="content" data-global-cms-content hidden>{{ old('content',$item->content ?? '') }}</textarea></div></section></main></div></form></div>
@include('partials.global-cms-editor')
@include('partials.global-cms-editor-script')
@endsection
@push('head')<meta name="csrf-token" content="{{ csrf_token() }}">@endpush
@push('styles')<style>.ne-card{border:1px solid rgba(103,208,234,.13);border-radius:15px;background:linear-gradient(145deg,#091f2b,#061720);padding:14px}.ne-card h2{margin:0 0 8px;font-size:11px;color:#e4f5f8}.ne-card label{display:block;margin-top:11px;color:#8ca8b2;font-size:9px;font-weight:700}.ne-card input,.ne-card textarea,.ne-card select{width:100%;box-sizing:border-box;margin-top:5px;padding:9px 10px;border:1px solid rgba(103,208,234,.13);border-radius:8px;background:#061823;color:#e9f8fb;outline:none;font-size:10px}.ne-card textarea{resize:vertical}.ne-card small{display:block;margin-top:4px;color:#607f89;font-size:7px}.ne-card .check{display:flex;align-items:center;gap:8px}.ne-card .check input{width:15px;margin:0}.ne-card .check span{color:#cce5ea;font-size:9px}@media(max-width:950px){form>div{grid-template-columns:1fr!important}} </style>@endpush
