@extends('layouts.portal')
@section('title','News & Event')
@section('content')
<div style="max-width:1400px;margin:auto;color:#eaf8fb">
<header style="display:flex;align-items:flex-end;justify-content:space-between;gap:18px;padding:5px 0 18px">
<div><div style="font-size:9px;font-weight:900;letter-spacing:.15em;color:#52d7ee">WEBSITE · NEWS & EVENT</div><h1 style="margin:5px 0;font-size:36px">News & Event</h1><p style="margin:0;color:#7897a3;font-size:11px">Manage news and announcements with the shared Canonical Editor.</p></div>
<a href="{{ route('admin.news_and_event.create') }}" style="display:inline-flex;align-items:center;gap:7px;min-height:40px;padding:0 13px;border-radius:10px;background:linear-gradient(135deg,#28b6d6,#168da8);color:#fff;text-decoration:none;font-size:10px;font-weight:800"><i class="fa-solid fa-plus"></i> New News / Event</a>
</header>
@if(session('status'))<div style="padding:10px 12px;border:1px solid rgba(66,201,155,.18);border-radius:10px;background:rgba(66,201,155,.07);color:#9ce5c9;font-size:10px;margin-bottom:12px">{{ session('status') }}</div>@endif
<form method="GET" style="display:flex;gap:8px;margin-bottom:14px"><input name="q" value="{{ $search }}" placeholder="Search news and events…" style="flex:1;min-height:38px;padding:0 12px;border-radius:9px;border:1px solid rgba(103,208,234,.12);background:#071923;color:#eaf8fb"><button style="padding:0 14px;border:0;border-radius:9px;background:#123746;color:#d9f6fa;font-weight:700">Search</button></form>
<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px">@forelse($items as $item)<article style="padding:15px;border:1px solid rgba(103,208,234,.12);border-radius:13px;background:linear-gradient(145deg,#091e29,#06151e)"><div style="display:flex;justify-content:space-between;gap:8px"><span style="color:#70d9ea;font-size:8px">{{ strtoupper($item->type) }}</span><b style="color:{{ $item->status==='published'?'#75ddb8':'#d6b66d' }};font-size:8px">{{ ucfirst($item->status) }}</b></div><h2 style="margin:12px 0 6px;font-size:16px">{{ $item->title }}</h2><p style="height:40px;margin:0;color:#7897a3;font-size:9px;line-height:1.55;overflow:hidden">{{ \Illuminate\Support\Str::limit(strip_tags($item->excerpt ?: $item->content ?: ''),140) ?: 'No description added yet.' }}</p><div style="display:flex;gap:5px;flex-wrap:wrap;margin-top:13px"><a href="{{ route('admin.news_and_event.edit',$item) }}" style="padding:7px 9px;border-radius:7px;border:1px solid rgba(103,208,234,.1);color:#9cc2cb;text-decoration:none;font-size:8px">Edit</a><form method="POST" action="{{ route('admin.news_and_event.toggle',$item) }}">@csrf @method('PATCH')<button style="padding:7px 9px;border-radius:7px;border:1px solid rgba(103,208,234,.1);background:transparent;color:#9cc2cb;font-size:8px">{{ $item->status==='published'?'Unpublish':'Publish' }}</button></form><form method="POST" action="{{ route('admin.news_and_event.destroy',$item) }}" onsubmit="return confirm('Delete this item?')">@csrf @method('DELETE')<button style="padding:7px 9px;border-radius:7px;border:1px solid rgba(217,128,140,.15);background:transparent;color:#d9808c;font-size:8px">Delete</button></form></div></article>@empty<div style="grid-column:1/-1;text-align:center;padding:65px 20px;border:1px dashed rgba(103,208,234,.18);border-radius:15px"><i class="fa-solid fa-newspaper" style="font-size:28px;color:#4ed5ed"></i><h2 style="font-size:18px;margin:14px 0 5px">No News & Event yet</h2><p style="color:#718e99;font-size:9px">Create your first news item or announcement using the Canonical Editor.</p><a href="{{ route('admin.news_and_event.create') }}" style="display:inline-flex;margin-top:10px;padding:9px 13px;border-radius:9px;background:#168da8;color:#fff;text-decoration:none;font-size:9px">Create First Item</a></div>@endforelse</div>
@if($items->hasPages())<div style="margin-top:15px">{{ $items->links() }}</div>@endif
</div>
@endsection
