@extends('layouts.public')

@php($siteName = $brand['name'] ?? config('fuelfree.company.name'))
@section('title', 'News & Notices — '.$siteName)
@section('content')
<style>
:root{color-scheme:dark;--bg:#031019;--surface:#071b25;--line:rgba(96,216,239,.16);--text:#edfaff;--muted:#8eaab4;--cyan:#51d8f0;--green:#64e0b2}
html,body{background:var(--bg)!important;color:var(--text)!important}
.newsroom{width:min(1180px,calc(100% - 32px));margin:0 auto;padding:52px 0 90px;background:var(--bg)!important;color:var(--text)!important}.newsroom *{box-sizing:border-box}.newsroom a,.newsroom a:visited,.newsroom a:hover,.newsroom a:active{color:inherit!important;text-decoration:none!important}
.news-mast{border-bottom:1px solid var(--line);padding-bottom:26px;margin-bottom:24px}.news-kicker{display:flex;align-items:center;gap:12px;color:var(--cyan)!important;font:800 9px/1.2 Inter,system-ui,sans-serif;letter-spacing:.22em;text-transform:uppercase}.news-kicker:after{content:"";height:1px;background:var(--line);flex:1}.news-mast h1{color:var(--text)!important;font:800 clamp(45px,6vw,82px)/.94 Inter,system-ui,sans-serif;letter-spacing:-.055em;margin:10px 0 14px}.news-mast p{max-width:720px;color:var(--muted)!important;font:400 15px/1.85 Inter,system-ui,sans-serif;margin:0}
.news-tools{display:grid;grid-template-columns:minmax(0,1fr) 125px 125px 125px;gap:10px;margin:22px 0 30px;align-items:stretch}.news-tools>*{min-height:48px;border:1px solid var(--line);border-radius:13px;background:rgba(7,27,37,.88)!important;color:var(--text)!important;display:flex;align-items:center;min-width:0}.search{padding:0 15px;gap:10px}.search i{color:var(--cyan)!important}.search input{width:100%;min-width:0;border:0!important;outline:0;background:transparent!important;color:var(--text)!important;font:500 10px Inter,system-ui,sans-serif}.search input::placeholder{color:#718d98!important}.filter{padding:0 13px;position:relative}.filter:after{content:"⌄";margin-left:auto;color:#86a7b1}.filter select{appearance:none;-webkit-appearance:none;border:0!important;outline:0;background:transparent!important;color:var(--text)!important;font:500 10px Inter,system-ui,sans-serif;width:100%;min-width:0}.filter select option{background:#071b25;color:#edfaff}.published-count{padding:0 12px;justify-content:center;color:var(--green)!important;white-space:nowrap;border-color:rgba(100,224,178,.22)!important;font:700 10px Inter,system-ui,sans-serif}.published-count i{margin-right:7px}
.lead{display:grid;grid-template-columns:minmax(300px,1fr) minmax(320px,1fr);border:1px solid var(--line);border-radius:22px;overflow:hidden;background:linear-gradient(145deg,#092632,#04141c)!important;margin-bottom:38px}.lead-media{aspect-ratio:1/1;background:#061923;position:relative;overflow:hidden}.lead-media img{width:100%;height:100%;object-fit:cover;display:block}.media-fallback{height:100%;display:grid;place-items:center;color:var(--cyan)!important;font-size:46px}.lead-copy{padding:34px;display:flex;flex-direction:column;justify-content:center}.label{display:inline-flex;align-self:flex-start;padding:7px 10px;border-radius:999px;background:rgba(81,216,240,.09)!important;border:1px solid rgba(81,216,240,.18)!important;color:var(--cyan)!important;font:800 8px Inter,system-ui,sans-serif;letter-spacing:.08em}.lead-copy h2{color:var(--text)!important;font:800 clamp(29px,4vw,48px)/1.08 Inter,system-ui,sans-serif;letter-spacing:-.035em;margin:15px 0}.lead-copy p{color:var(--muted)!important;font:400 14px/1.8 Arial,sans-serif;margin:0 0 18px}.meta{display:flex;align-items:center;gap:12px;color:#789aa5!important;font:500 9px Inter,system-ui,sans-serif}.read{display:inline-flex;align-items:center;gap:8px;color:var(--cyan)!important;font:800 10px Inter,system-ui,sans-serif;margin-top:18px}
.section-head{display:flex;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:12px;margin-bottom:12px}.section-head h2{color:var(--text)!important;font:800 clamp(29px,4vw,48px)/1.2 Inter,system-ui,sans-serif;letter-spacing:-.025em;margin:5px 0 0}.section-head span{color:var(--cyan)!important;font:800 9px/1.2 Inter,system-ui,sans-serif;letter-spacing:.15em;text-transform:uppercase}.empty{padding:40px 25px;border:1px dashed var(--line);border-radius:17px;color:var(--muted)!important;background:rgba(7,27,37,.35)!important;text-align:center;font:500 14px Arial,sans-serif}.pager{padding-top:25px}
@media(max-width:900px){.newsroom{width:min(100% - 24px,700px);padding:38px 0 70px}.news-tools{grid-template-columns:minmax(0,1fr) 105px 105px 105px}.lead{grid-template-columns:1fr}}
@media(max-width:560px){.newsroom{width:calc(100% - 24px);padding:30px 0 60px}.news-mast{padding-bottom:20px;margin-bottom:18px}.news-mast h1{font-size:44px}.news-mast p{font-size:13px}.news-tools{grid-template-columns:minmax(0,1fr) 62px 62px 82px;gap:6px;margin-bottom:22px}.news-tools>*{min-height:45px;border-radius:11px}.search{padding:0 10px;gap:7px}.search input{font-size:11px}.search input::placeholder{font-size:10px}.filter{padding:0 8px}.filter select{font-size:10px}.published-count{padding:0 6px;font-size:9px}.published-count i{margin-right:4px}.lead{border-radius:17px;margin-bottom:28px}.lead-copy{padding:21px}.lead-copy h2{font-size:29px}.lead-copy p{font-size:12px}.section-head h2{font-size:29px}.section-head span{font-size:8px}}

/* EXACT HOMEPAGE NEWS CARD — shared with home-v3 */
.news-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.news{display:grid;grid-template-columns:220px 32px minmax(0,1fr);width:100%;height:220px;overflow:hidden;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,rgba(8,37,50,.9),rgba(3,19,27,.94));transition:transform .25s,border-color .25s}.news:hover{transform:translateY(-3px);border-color:rgba(72,216,241,.4)}.news-media{width:220px;height:220px;aspect-ratio:1/1;background:radial-gradient(circle at 50% 50%,rgba(72,216,241,.16),transparent 50%),#061923;overflow:hidden}.news-media img{width:100%;height:100%;display:block;object-fit:cover}.news-placeholder{width:100%;height:100%;display:grid;place-items:center;color:#48d8f1;font-size:30px}.news-kind{height:100%;display:flex;align-items:center;justify-content:center;border-left:1px solid rgba(72,216,241,.1);border-right:1px solid rgba(72,216,241,.1);color:var(--cyan);font-size:8px;font-weight:800;letter-spacing:.16em;writing-mode:vertical-rl;transform:rotate(180deg);text-transform:uppercase}.news-kind.notice{color:#f0c58e}.news-body{height:220px;overflow:hidden;padding:18px 18px 16px;display:flex;flex-direction:column;min-width:0}.news h3{margin:0 0 7px;font-size:17px;line-height:1.35;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.news p{color:var(--muted);font-size:10px;line-height:1.65;margin:0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.news-footer{margin-top:auto;padding-top:12px;display:flex;align-items:center;justify-content:space-between;gap:8px}.date{color:#6f9aa5;font-size:8px}.read{color:var(--cyan);font-size:9px;font-weight:700;white-space:nowrap}
@media(max-width:650px){.news-grid{grid-template-columns:1fr;gap:10px}.news{grid-template-columns:112px 24px minmax(0,1fr);width:100%;height:112px;min-height:112px;align-items:stretch}.news-media{width:112px;height:112px;min-width:112px;min-height:112px;aspect-ratio:1/1}.news-media img{width:112px;height:112px;object-fit:cover}.news-kind{font-size:7px;letter-spacing:.11em}.news-body{width:100%;height:112px;min-height:112px;padding:11px 13px;overflow:hidden}.news h3{font-size:14px;line-height:1.3;margin:0;-webkit-line-clamp:2}.news p{display:none}.news-footer{padding-top:5px}.date{font-size:8px}.read{font-size:8px}}
@media(max-width:400px){.news{grid-template-columns:100px 22px minmax(0,1fr);height:100px;min-height:100px}.news-media,.news-media img{width:100px;height:100px;min-width:100px;min-height:100px}.news-body{height:100px;min-height:100px;padding:9px 11px}.news h3{font-size:13px}.news-kind{font-size:6px}}
</style>

<main class="newsroom">
    <header class="news-mast"><div class="news-kicker">Latest updates</div><h1>News &amp; Notices</h1><p>Stay informed with the latest announcements, achievements and important updates from {{ $siteName }}.</p></header>
    <div class="news-tools"><form class="search" method="GET" action="{{ route('news.index') }}"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><input type="search" name="q" value="{{ request('q') }}" placeholder="Search news..." aria-label="Search news"></form><label class="filter"><select name="type" onchange="this.form.submit()" form="news-filter"><option value="">All</option><option value="news" @selected(request('type')==='news')>News</option><option value="announcement" @selected(request('type')==='announcement')>Notice</option></select></label><label class="filter"><select name="sort" onchange="this.form.submit()" form="news-filter"><option value="newest" @selected(request('sort','newest')==='newest')>Newest</option><option value="oldest" @selected(request('sort')==='oldest')>Oldest</option></select></label><div class="published-count"><i class="fa-regular fa-newspaper"></i>{{ $publishedCount }} Published</div></div><form id="news-filter" method="GET" action="{{ route('news.index') }}"><input type="hidden" name="q" value="{{ request('q') }}"></form>
    <section><div class="section-head"><div><span>From the newsroom</span><h2>Latest publications</h2></div><span>{{ $news->total() }} stories</span></div>@if($news->isEmpty())<div class="empty">No published news or notices are available yet.</div>@else<div class="news-grid">@foreach($news as $item)<a class="news" href="{{ route('news.show',$item->slug) }}"><div class="news-media">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" alt="{{ $item->cover_alt ?: $item->title }}" loading="lazy">@else<div class="media-fallback"><i class="fa-regular fa-newspaper"></i></div>@endif</div><div class="news-kind {{ $item->type==='announcement'?'notice':'' }}">{{ $item->type==='announcement'?'Notice':'News' }}</div><div class="news-body"><h3>{{ $item->title }}</h3><div class="news-footer"><span class="date">{{ $item->published_at?->format('d F Y') }}</span><span class="read">Read more →</span></div></div></a>@endforeach</div><div class="pager">{{ $news->links() }}</div>@endif</section>
</main>
@endsection
