@extends('layouts.public')

@php($siteName = $brand['name'] ?? config('fuelfree.company.name'))
@section('title', 'News & Notices — '.$siteName)
@section('content')
<style>:root{--bg:#031018;--card:rgba(9,39,52,.82);--line:rgba(110,220,240,.14);--text:#edfaff;--muted:#8caab7;--accent:#45c8e8;--gold:#f1d27c}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,rgba(69,200,232,.15),transparent 35%),var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}a{color:inherit;text-decoration:none}.shell{width:min(1120px,calc(100% - 28px));margin:auto}.hero{padding:70px 0 35px}.eyebrow{font-size:10px;letter-spacing:.18em;color:var(--accent);text-transform:uppercase}.hero h1{font-size:clamp(38px,6vw,68px);line-height:1;margin:10px 0}.hero p{color:var(--muted);max-width:700px;line-height:1.7}.featured{display:grid;grid-template-columns:1.15fr 1fr;margin-bottom:28px;border:1px solid var(--line);border-radius:22px;overflow:hidden;background:linear-gradient(145deg,rgba(9,39,52,.9),rgba(5,24,33,.85))}.featured-media{min-height:310px;background:#061923}.featured-media img{width:100%;height:100%;object-fit:cover;display:block}.featured-copy{padding:clamp(22px,4vw,42px);display:flex;flex-direction:column;justify-content:center}.badge{display:inline-flex;align-self:flex-start;gap:6px;padding:6px 9px;border-radius:999px;background:rgba(241,210,124,.09);border:1px solid rgba(241,210,124,.18);color:var(--gold);font-size:8px;font-weight:800}.featured-copy h2{font-size:clamp(26px,4vw,42px);line-height:1.1;margin:14px 0}.featured-copy p{color:var(--muted);font-size:12px;line-height:1.7}.date{color:#6f9aa8;font-size:10px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding-bottom:50px}.card{border:1px solid var(--line);border-radius:20px;overflow:hidden;background:linear-gradient(145deg,var(--card),rgba(5,24,33,.82));transition:.25s}.card:hover{transform:translateY(-4px);border-color:rgba(69,200,232,.35)}.thumb{height:180px;background:radial-gradient(circle at 50% 50%,rgba(69,200,232,.18),transparent 45%),#061923;display:grid;place-items:center;overflow:hidden}.thumb img{width:100%;height:100%;object-fit:cover}.thumb i{font-size:38px;color:#45c8e8;filter:drop-shadow(0 0 16px rgba(69,200,232,.45))}.body{padding:18px}.type{display:inline-flex;padding:5px 7px;border-radius:999px;font-size:7px;font-weight:800;letter-spacing:.06em;margin-bottom:8px}.news{color:#8ce5f4;background:rgba(69,200,232,.1)}.notice{color:#f0c58e;background:rgba(220,153,68,.1)}.body h2{font-size:18px;margin:8px 0}.body p{color:var(--muted);font-size:12px;line-height:1.65}.read{display:inline-flex;gap:7px;align-items:center;color:var(--accent);font-size:11px;font-weight:700;margin-top:8px}.empty{padding:35px;border:1px dashed var(--line);border-radius:18px;color:var(--muted)}.pager{padding:20px 0 55px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.featured{grid-template-columns:1fr}.featured-media{min-height:250px}}@media(max-width:540px){.hero{padding:48px 0 25px}.grid{grid-template-columns:1fr}.thumb{height:200px}.featured-media{min-height:210px}}</style>
<main class="shell"><section class="hero"><span class="eyebrow">FuelFree PowerPlant</span><h1>News &amp; Notices</h1><p>Latest news, official notices, announcements and developments from {{ $siteName }}.</p></section>
@if($featured)<a class="featured" href="{{ route('news.show',$featured->slug) }}"><div class="featured-media">@if($featured->image_path)<img src="{{ asset('storage/'.$featured->image_path) }}" alt="{{ $featured->cover_alt ?: $featured->title }}">@else<i class="fa-regular fa-newspaper"></i>@endif</div><div class="featured-copy"><span class="badge"><i class="fa-solid fa-star"></i> FEATURED</span><span class="date">{{ $featured->published_at?->format('d F Y') }}</span><h2>{{ $featured->title }}</h2><p>{{ $featured->excerpt ?: \Illuminate\Support\Str::limit(strip_tags($featured->content),190) }}</p><span class="read">Read publication <i class="fa-solid fa-arrow-right"></i></span></div></a>@endif
@if($news->isEmpty())<div class="empty">No published news or notices are available yet.</div>@else<div class="grid">@foreach($news as $item)<article class="card"><div class="thumb">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" alt="{{ $item->cover_alt ?: $item->title }}" loading="lazy">@else<i class="fa-regular fa-newspaper"></i>@endif</div><div class="body"><span class="type {{ $item->type==='announcement'?'notice':'news' }}">{{ $item->type==='announcement'?'NOTICE':'NEWS' }}</span><span class="date">{{ $item->published_at?->format('d M Y') }}</span><h2>{{ $item->title }}</h2><p>{{ $item->excerpt ?: \Illuminate\Support\Str::limit(strip_tags($item->content),150) }}</p><a class="read" href="{{ route('news.show',$item->slug) }}">Read more <i class="fa-solid fa-arrow-right"></i></a></div></article>@endforeach</div><div class="pager">{{ $news->links() }}</div>@endif</main>
@endsection
