@extends('layouts.public')

@php($siteName = $brand['name'] ?? config('fuelfree.company.name'))
@section('title', 'News & Notices — '.$siteName)
@section('content')
<style>
:root{color-scheme:dark;--bg:#031019;--surface:#071b25;--line:rgba(96,216,239,.16);--text:#edfaff;--muted:#8eaab4;--cyan:#51d8f0;--green:#64e0b2}
html,body{background:var(--bg)!important;color:var(--text)!important}
.newsroom{width:min(1180px,calc(100% - 32px));margin:0 auto;padding:52px 0 90px;background:var(--bg)!important;color:var(--text)!important}.newsroom *{box-sizing:border-box}.newsroom a,.newsroom a:visited,.newsroom a:hover,.newsroom a:active{color:inherit!important;text-decoration:none!important}
.news-mast{border-bottom:1px solid var(--line);padding-bottom:26px;margin-bottom:24px}.news-kicker{display:flex;align-items:center;gap:12px;color:var(--cyan)!important;font:800 11px/1.2 Arial,sans-serif;letter-spacing:.22em;text-transform:uppercase}.news-kicker:after{content:"";height:1px;background:var(--line);flex:1}.news-mast h1{color:var(--text)!important;font:800 clamp(42px,7vw,76px)/.96 Arial,sans-serif;letter-spacing:-.055em;margin:10px 0 14px}.news-mast p{max-width:720px;color:var(--muted)!important;font:400 15px/1.75 Arial,sans-serif;margin:0}
.news-tools{display:grid;grid-template-columns:minmax(0,1fr) 150px 150px auto;gap:10px;margin:22px 0 30px}.news-tools>*{min-height:48px;border:1px solid var(--line);border-radius:13px;background:rgba(7,27,37,.88)!important;color:var(--text)!important;display:flex;align-items:center}.search{padding:0 15px;gap:10px}.search i{color:var(--cyan)!important}.search input{width:100%;border:0!important;outline:0;background:transparent!important;color:var(--text)!important;font:500 14px Arial,sans-serif}.search input::placeholder{color:#718d98!important}.filter{padding:0 13px;position:relative}.filter:after{content:"⌄";margin-left:auto;color:#86a7b1}.filter select{appearance:none;-webkit-appearance:none;border:0!important;outline:0;background:transparent!important;color:var(--text)!important;font:500 13px Arial,sans-serif;width:100%}.filter select option{background:#071b25;color:#edfaff}.published-count{padding:0 16px;justify-content:center;color:var(--green)!important;white-space:nowrap;border-color:rgba(100,224,178,.22)!important;font:700 11px Arial,sans-serif}.published-count i{margin-right:7px}
.lead{display:grid;grid-template-columns:minmax(300px,1fr) minmax(320px,1fr);border:1px solid var(--line);border-radius:22px;overflow:hidden;background:linear-gradient(145deg,#092632,#04141c)!important;margin-bottom:38px}.lead-media{aspect-ratio:1/1;background:#061923;position:relative;overflow:hidden}.lead-media img{width:100%;height:100%;object-fit:cover;display:block}.media-fallback{height:100%;display:grid;place-items:center;color:var(--cyan)!important;font-size:46px}.lead-copy{padding:34px;display:flex;flex-direction:column;justify-content:center}.label{display:inline-flex;align-self:flex-start;padding:7px 10px;border-radius:999px;background:rgba(81,216,240,.09)!important;border:1px solid rgba(81,216,240,.18)!important;color:var(--cyan)!important;font:800 9px Arial,sans-serif;letter-spacing:.08em}.lead-copy h2{color:var(--text)!important;font:800 clamp(30px,4vw,48px)/1.08 Arial,sans-serif;letter-spacing:-.035em;margin:15px 0}.lead-copy p{color:var(--muted)!important;font:400 14px/1.8 Arial,sans-serif;margin:0 0 18px}.meta{display:flex;align-items:center;gap:12px;color:#789aa5!important;font:500 10px Arial,sans-serif}.read{display:inline-flex;align-items:center;gap:8px;color:var(--cyan)!important;font:800 11px Arial,sans-serif;margin-top:18px}
.section-head{display:flex;align-items:end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:12px;margin-bottom:6px}.section-head h2{color:var(--text)!important;font:800 26px/1.2 Arial,sans-serif;letter-spacing:-.025em;margin:5px 0 0}.section-head span{color:var(--cyan)!important;font:800 9px/1.2 Arial,sans-serif;letter-spacing:.15em;text-transform:uppercase}.paper-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));column-gap:30px}.story{display:grid;grid-template-columns:150px minmax(0,1fr);gap:16px;padding:18px 0;border-bottom:1px solid var(--line);min-width:0;transition:transform .18s ease}.story:hover{transform:translateY(-2px)}.story-media{width:150px;height:150px;aspect-ratio:1/1;border-radius:11px;overflow:hidden;background:#061923;border:1px solid rgba(81,216,240,.09)}.story-media img{width:100%;height:100%;object-fit:cover;display:block}.story-body{min-width:0;display:flex;flex-direction:column;justify-content:center}.story-type{color:var(--cyan)!important;font:800 8px/1.2 Arial,sans-serif;letter-spacing:.12em}.story h3{color:var(--text)!important;font:800 19px/1.3 Arial,sans-serif;letter-spacing:-.02em;margin:7px 0}.story p{color:var(--muted)!important;font:400 11px/1.65 Arial,sans-serif;margin:0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.story .meta{margin-top:9px}.story .meta span:last-child{color:var(--cyan)!important}.empty{padding:40px 25px;border:1px dashed var(--line);border-radius:17px;color:var(--muted)!important;background:rgba(7,27,37,.35)!important;text-align:center;font:500 14px Arial,sans-serif}.pager{padding-top:25px}
@media(max-width:900px){.newsroom{width:min(100% - 24px,700px);padding:38px 0 70px}.news-tools{grid-template-columns:1fr 1fr}.search{grid-column:1/-1}.published-count{grid-column:1/-1}.lead{grid-template-columns:1fr}.paper-list{grid-template-columns:1fr}.story{grid-template-columns:140px minmax(0,1fr)}.story-media{width:140px;height:140px}}
@media(max-width:560px){.newsroom{width:calc(100% - 24px);padding:30px 0 60px}.news-mast{padding-bottom:20px;margin-bottom:18px}.news-mast h1{font-size:43px}.news-mast p{font-size:13px}.news-tools{gap:8px;margin-bottom:22px}.news-tools>*{min-height:45px;border-radius:11px}.filter{padding:0 11px}.published-count{font-size:10px}.lead{border-radius:17px;margin-bottom:28px}.lead-copy{padding:21px}.lead-copy h2{font-size:27px}.lead-copy p{font-size:12px}.section-head h2{font-size:22px}.paper-list{display:block}.story{grid-template-columns:104px minmax(0,1fr);gap:12px;padding:15px 0}.story-media{width:104px;height:104px;border-radius:9px}.story h3{font-size:16px;line-height:1.25;margin:5px 0}.story p{font-size:9px;line-height:1.55}.story .meta{font-size:8px;margin-top:6px;gap:8px}.section-head span{font-size:8px}}
</style>

<main class="newsroom">
    <header class="news-mast"><div class="news-kicker">Latest updates</div><h1>News &amp; Notices</h1><p>Stay informed with the latest announcements, achievements and important updates from {{ $siteName }}.</p></header>
    <div class="news-tools"><form class="search" method="GET" action="{{ route('news.index') }}"><i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i><input type="search" name="q" value="{{ request('q') }}" placeholder="Search news..." aria-label="Search news"></form><label class="filter"><select name="type" onchange="this.form.submit()" form="news-filter"><option value="">All</option><option value="news" @selected(request('type')==='news')>News</option><option value="announcement" @selected(request('type')==='announcement')>Notice</option></select></label><label class="filter"><select name="sort" onchange="this.form.submit()" form="news-filter"><option value="newest" @selected(request('sort','newest')==='newest')>Newest</option><option value="oldest" @selected(request('sort')==='oldest')>Oldest</option></select></label><div class="published-count"><i class="fa-regular fa-newspaper"></i>{{ $publishedCount }} Published</div></div><form id="news-filter" method="GET" action="{{ route('news.index') }}"><input type="hidden" name="q" value="{{ request('q') }}"></form>
    @if($featured)<a class="lead" href="{{ route('news.show',$featured->slug) }}"><div class="lead-media">@if($featured->image_path)<img src="{{ asset('storage/'.$featured->image_path) }}" alt="{{ $featured->cover_alt ?: $featured->title }}">@else<div class="media-fallback"><i class="fa-regular fa-newspaper"></i></div>@endif</div><div class="lead-copy"><span class="label">{{ $featured->type==='announcement'?'NOTICE':'NEWS' }} · FEATURED</span><h2>{{ $featured->title }}</h2><p>{{ $featured->excerpt ?: \Illuminate\Support\Str::limit(strip_tags($featured->content),220) }}</p><div class="meta"><span>{{ $featured->published_at?->format('d F Y') }}</span><span>•</span><span>{{ $siteName }}</span></div><span class="read">Read full publication <i class="fa-solid fa-arrow-right"></i></span></div></a>@endif
    <section><div class="section-head"><div><span>From the newsroom</span><h2>Latest publications</h2></div><span>{{ $news->total() }} stories</span></div>@if($news->isEmpty())<div class="empty">No published news or notices are available yet.</div>@else<div class="paper-list">@foreach($news as $item)<a class="story" href="{{ route('news.show',$item->slug) }}"><div class="story-media">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" alt="{{ $item->cover_alt ?: $item->title }}" loading="lazy">@else<div class="media-fallback"><i class="fa-regular fa-newspaper"></i></div>@endif</div><div class="story-body"><span class="story-type">{{ $item->type==='announcement'?'NOTICE':'NEWS' }}</span><h3>{{ $item->title }}</h3><p>{{ $item->excerpt ?: \Illuminate\Support\Str::limit(strip_tags($item->content),120) }}</p><div class="meta"><span>{{ $item->published_at?->format('d M Y') }}</span><span>Read more →</span></div></div></a>@endforeach</div><div class="pager">{{ $news->links() }}</div>@endif</section>
</main>
@endsection
