@extends('layouts.public')

@php($siteName = $brand['name'] ?? config('fuelfree.company.name'))

@section('title', $article->title.' — '.$siteName)

@section('content')
<style>:root{--bg:#031018;--card:rgba(9,39,52,.82);--line:rgba(110,220,240,.14);--text:#edfaff;--muted:#8caab7;--accent:#45c8e8}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 75% 0,rgba(69,200,232,.14),transparent 36%),var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}a{color:inherit}.shell{width:min(900px,calc(100% - 28px));margin:auto}.top{padding:28px 0}.back{color:var(--accent);font-size:12px;text-decoration:none}.article{border:1px solid var(--line);border-radius:24px;overflow:hidden;background:linear-gradient(145deg,var(--card),rgba(5,24,33,.82));margin-bottom:50px}.cover{max-height:430px;background:#061923}.cover img{display:block;width:100%;max-height:430px;object-fit:cover}.copy{padding:clamp(22px,5vw,48px)}.eyebrow{font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:var(--accent)}h1{font-size:clamp(34px,6vw,60px);line-height:1.05;margin:12px 0}.date{color:#6f9aa8;font-size:11px}.content{margin-top:28px;color:#b9cdd4;font-size:15px;line-height:1.9}.content p{margin:0 0 18px}.related{margin-bottom:60px}.related h2{font-size:24px}.related-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.related a{padding:16px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.025);text-decoration:none}.related small{color:#6f9aa8}.related strong{display:block;margin-top:7px;font-size:14px}@media(max-width:650px){.related-grid{grid-template-columns:1fr}}</style>
<main class="shell"><div class="top"><a class="back" href="{{ route('news.index') }}"><i class="fa-solid fa-arrow-left"></i> Back to News</a></div><article class="article">@if($article->image_path)<div class="cover"><img src="{{ asset('storage/'.$article->image_path) }}" alt="{{ $article->title }}"></div>@endif<div class="copy"><span class="eyebrow">News &amp; Updates</span><h1>{{ $article->title }}</h1><span class="date">{{ $article->published_at?->format('d F Y') }}</span><div class="content">{!! $article->content !!}</div></div></article>@if($related->isNotEmpty())<section class="related"><h2>More updates</h2><div class="related-grid">@foreach($related as $item)<a href="{{ route('news.show',$item->slug) }}"><small>{{ $item->published_at?->format('d M Y') }}</small><strong>{{ $item->title }}</strong></a>@endforeach</div></section>@endif</main>
@endsection
